const copy={
  hi:{eyebrow:'आपकी मदद, आपकी भाषा में',title:'किस काम में\nमदद चाहिए?',subtitle:'बोलकर या लिखकर बताइए। हम एक-एक कदम साथ चलेंगे।',micTitle:'बोलने के लिए छुएँ',micHint:'जैसे आप आम तौर पर बोलती हैं, वैसे बोलें',orType:'या यहाँ लिखें',inputLabel:'अपना सवाल लिखें',placeholder:'उदाहरण: मुझे विधवा पेंशन चाहिए',privacy:'आपका संदेश जवाब के लिए OpenAI को भेजा जाता है। आधार, OTP, PIN या बैंक की जानकारी साझा न करें।',quickTitle:'या कोई विषय चुनें',topicPension:'पेंशन और सहायता',topicHealth:'स्वास्थ्य सेवा',topicDocs:'मेरे दस्तावेज़',topicWork:'काम और कौशल',answerLabel:'आपके अगले कदम',officialCaption:'आगे की जानकारी सरकारी वेबसाइट पर मिलेगी।',trust:'सारी जानकारी यहीं देखें। सरकारी पेज आप चाहें तभी खोलें।',moreServices:'और सेवाएँ देखें ↗',footer:'शुरुआत करने में आपकी साथी',notGov:'यह सरकारी वेबसाइट नहीं है',listening:'सुन रही हूँ… अब बोलिए',voiceUnsupported:'इस ब्राउज़र में आवाज़ से लिखना उपलब्ध नहीं है। नीचे लिखकर बताइए।',noSpeech:'आवाज़ समझ नहीं आई। फिर कोशिश करें या लिखकर बताइए।',placeholderResponse:'अपनी बात लिखें या कोई विषय चुनें।',linkScheme:'सरकारी योजनाएँ देखें',linkServices:'सरकारी सेवाएँ देखें',pension:'पेंशन या आर्थिक सहायता',health:'स्वास्थ्य सहायता',documents:'ज़रूरी दस्तावेज़',work:'काम या नया कौशल',stepsScheme:['अपनी उम्र, राज्य और ज़रूरत के हिसाब से योजनाएँ खोजें।','जिस योजना में रुचि हो, उसकी पात्रता और ज़रूरी दस्तावेज़ देखें।','आवेदन का तरीका पढ़ें। कोई जानकारी समझ न आए तो यहाँ पूछें।'],stepsServices:['पहले अपनी ज़रूरत चुनें। सरकारी सेवा की सूची खुलेगी।','अपने राज्य या विभाग की सेवा ढूँढ़ें।','आगे बढ़ने से पहले फीस, दस्तावेज़ और आधिकारिक पते की जाँच करें।'],note:'पात्रता और नियम राज्य के अनुसार अलग हो सकते हैं। किसी को OTP, PIN या बैंक का पासवर्ड न बताएं।',sent:'आपका सवाल',tapTopic:'यह विषय चुना गया'},
  en:{eyebrow:'HELP, IN YOUR LANGUAGE',title:'What would you\nlike help with?',subtitle:'Say it or type it. We’ll take it one small step at a time.',micTitle:'Tap to speak',micHint:'Speak naturally, in your own words',orType:'OR TYPE HERE',inputLabel:'Type your question',placeholder:'For example: I need help finding a pension',privacy:'Your question and selected state are sent to OpenAI for an answer. Never share Aadhaar, OTP, PIN, or bank details.',quickTitle:'OR PICK A TOPIC',topicPension:'Pension & support',topicHealth:'Health care',topicDocs:'My documents',topicWork:'Work & skills',answerLabel:'YOUR NEXT STEPS',officialCaption:'Check the official page before you apply.',trust:'Read the details here. Open an official page only if you choose.',moreServices:'Explore services ↗',footer:'A friendly guide to getting started',notGov:'Not a government website',listening:'Listening… go ahead',voiceUnsupported:'Voice input is not available in this browser. You can type below.',noSpeech:'I didn’t catch that. Try again or type your question.',placeholderResponse:'Type what you need or choose a topic.',linkScheme:'Explore government schemes',linkServices:'Explore government services',pension:'Pension or financial support',health:'Health support',documents:'Important documents',work:'Work or learn a skill',stepsScheme:['Look for schemes based on your age, state, and what you need.','Open a scheme to check who can apply and which documents are needed.','Read how to apply. Ask here if any step is unclear.'],stepsServices:['Choose the kind of help you need to see government services.','Find the service for your state or department.','Before continuing, check the fee, documents, and official web address.'],note:'Eligibility and rules can vary by state. Never share your OTP, PIN, or banking password.',sent:'You asked',tapTopic:'You chose'},
  bn:{eyebrow:'আপনার ভাষায় আপনার সহায়ক',title:'কী বিষয়ে\nসাহায্য চান?',subtitle:'বলুন বা লিখুন। আমরা ধাপে ধাপে এগোব।',micTitle:'বলতে ট্যাপ করুন',micHint:'নিজের মতো করে স্বাভাবিকভাবে বলুন',orType:'অথবা এখানে লিখুন',inputLabel:'আপনার প্রশ্ন লিখুন',placeholder:'যেমন: পেনশন পেতে সাহায্য চাই',privacy:'এই ডেমোতে আপনার প্রশ্ন এই ডিভাইসেই থাকে।',quickTitle:'অথবা একটি বিষয় বেছে নিন',topicPension:'পেনশন ও সহায়তা',topicHealth:'স্বাস্থ্যসেবা',topicDocs:'আমার নথি',topicWork:'কাজ ও দক্ষতা',answerLabel:'আপনার পরবর্তী ধাপ',officialCaption:'পরের ধাপে সরকারি ওয়েবসাইটে যাবেন।',trust:'সহজ নির্দেশনা। সরকারি ওয়েবসাইটের লিঙ্ক।',moreServices:'সব পরিষেবা দেখুন ↗',footer:'শুরু করার সহায়ক সঙ্গী',notGov:'এটি সরকারি ওয়েবসাইট নয়',listening:'শুনছি… বলুন',voiceUnsupported:'এই ব্রাউজারে ভয়েস ইনপুট নেই। নিচে লিখে জানান।',noSpeech:'বুঝতে পারিনি। আবার বলুন বা লিখুন।',placeholderResponse:'আপনার প্রয়োজন লিখুন বা একটি বিষয় বেছে নিন।',linkScheme:'সরকারি প্রকল্প দেখুন',linkServices:'সরকারি পরিষেবা দেখুন',pension:'পেনশন বা আর্থিক সহায়তা',health:'স্বাস্থ্য সহায়তা',documents:'জরুরি নথি',work:'কাজ বা নতুন দক্ষতা',stepsScheme:['আপনার বয়স, রাজ্য ও প্রয়োজন অনুযায়ী প্রকল্প খুঁজুন।','কোন প্রকল্পে আবেদন করতে পারবেন এবং কী নথি লাগবে দেখুন।','আবেদনের পদ্ধতি পড়ুন। কিছু বুঝতে অসুবিধা হলে এখানে জিজ্ঞাসা করুন।'],stepsServices:['আপনার প্রয়োজন বেছে নিয়ে সরকারি পরিষেবার তালিকা দেখুন।','আপনার রাজ্য বা দপ্তরের পরিষেবাটি খুঁজুন।','চালিয়ে যাওয়ার আগে ফি, নথি এবং সরকারি ওয়েব ঠিকানা যাচাই করুন।'],note:'যোগ্যতা ও নিয়ম রাজ্যভেদে আলাদা হতে পারে। OTP, PIN বা ব্যাঙ্কের পাসওয়ার্ড কাউকে বলবেন না।',sent:'আপনার প্রশ্ন',tapTopic:'আপনি বেছে নিয়েছেন'},
  ta:{eyebrow:'உங்கள் மொழியில் உதவி',title:'எதில் உதவி\nவேண்டும்?',subtitle:'பேசுங்கள் அல்லது எழுதுங்கள். படிப்படியாகச் செய்வோம்.',micTitle:'பேசத் தொட தட்டவும்',micHint:'உங்கள் வழக்கமான பேச்சில் சொல்லுங்கள்',orType:'அல்லது இங்கே எழுதுங்கள்',inputLabel:'உங்கள் கேள்வியை எழுதுங்கள்',placeholder:'உதாரணம்: ஓய்வூதியம் பெற உதவி வேண்டும்',privacy:'இந்த மாதிரியில் உங்கள் கேள்வி இந்தச் சாதனத்தில் மட்டுமே இருக்கும்.',quickTitle:'அல்லது ஒரு தலைப்பைத் தேர்ந்தெடுக்கவும்',topicPension:'ஓய்வூதியம் & உதவி',topicHealth:'மருத்துவ சேவை',topicDocs:'என் ஆவணங்கள்',topicWork:'வேலை & திறன்கள்',answerLabel:'அடுத்த படிகள்',officialCaption:'அடுத்ததாக அரசு இணையதளத்திற்குச் செல்வீர்கள்.',trust:'எளிய வழிகாட்டல். அரசு இணையதள இணைப்புகள்.',moreServices:'சேவைகளைப் பார்க்க ↗',footer:'தொடங்க உதவும் தோழி',notGov:'இது அரசு இணையதளம் அல்ல',listening:'கேட்கிறேன்… சொல்லுங்கள்',voiceUnsupported:'இந்த உலாவியில் குரல் உள்ளீடு இல்லை. கீழே எழுதலாம்.',noSpeech:'புரியவில்லை. மீண்டும் முயற்சிக்கவும் அல்லது எழுதவும்.',placeholderResponse:'உங்கள் தேவையை எழுதுங்கள் அல்லது தலைப்பைத் தேர்ந்தெடுக்கவும்.',linkScheme:'அரசுத் திட்டங்களைப் பார்க்க',linkServices:'அரசு சேவைகளைப் பார்க்க',pension:'ஓய்வூதியம் அல்லது நிதி உதவி',health:'மருத்துவ உதவி',documents:'முக்கிய ஆவணங்கள்',work:'வேலை அல்லது திறன் பயிற்சி',stepsScheme:['வயது, மாநிலம் மற்றும் தேவைக்கேற்ப திட்டங்களைத் தேடுங்கள்.','விண்ணப்பிக்கத் தகுதி மற்றும் தேவையான ஆவணங்களைப் பாருங்கள்.','விண்ணப்பிக்கும் முறையைப் படியுங்கள். புரியவில்லை என்றால் இங்கே கேளுங்கள்.'],stepsServices:['தேவையைத் தேர்ந்தெடுத்து அரசு சேவைகளைப் பாருங்கள்.','உங்கள் மாநிலம் அல்லது துறைக்கான சேவையைக் கண்டறியுங்கள்.','தொடர்வதற்கு முன் கட்டணம், ஆவணங்கள், அரசு இணைய முகவரியைச் சரிபாருங்கள்.'],note:'தகுதி மற்றும் விதிகள் மாநிலத்துக்கு மாநிலம் மாறலாம். OTP, PIN அல்லது வங்கி கடவுச்சொல்லைப் பகிர வேண்டாம்.',sent:'உங்கள் கேள்வி',tapTopic:'நீங்கள் தேர்ந்தெடுத்தது'},
  te:{eyebrow:'మీ భాషలో మీకు సహాయం',title:'దేనిలో సహాయం\nకావాలి?',subtitle:'చెప్పండి లేదా టైప్ చేయండి. ఒక్కో అడుగు కలిసి చేద్దాం.',micTitle:'మాట్లాడటానికి నొక్కండి',micHint:'మీకు సహజంగా అనిపించినట్లు చెప్పండి',orType:'లేదా ఇక్కడ టైప్ చేయండి',inputLabel:'మీ ప్రశ్న టైప్ చేయండి',placeholder:'ఉదాహరణ: పెన్షన్ పొందడంలో సహాయం కావాలి',privacy:'ఈ డెమోలో మీ ప్రశ్న ఈ పరికరంలోనే ఉంటుంది.',quickTitle:'లేదా ఒక అంశాన్ని ఎంచుకోండి',topicPension:'పెన్షన్ & సహాయం',topicHealth:'ఆరోగ్య సేవ',topicDocs:'నా పత్రాలు',topicWork:'పని & నైపుణ్యాలు',answerLabel:'తదుపరి అడుగులు',officialCaption:'తర్వాత ప్రభుత్వ వెబ్‌సైట్‌లో కొనసాగుతారు.',trust:'సులభమైన సూచనలు. అధికారిక ప్రభుత్వ లింకులు.',moreServices:'సేవలను చూడండి ↗',footer:'ప్రారంభించేందుకు మీ తోడు',notGov:'ఇది ప్రభుత్వ వెబ్‌సైట్ కాదు',listening:'వింటున్నాను… చెప్పండి',voiceUnsupported:'ఈ బ్రౌజర్‌లో వాయిస్ ఇన్‌పుట్ లేదు. కింద టైప్ చేయవచ్చు.',noSpeech:'అర్థం కాలేదు. మళ్లీ ప్రయత్నించండి లేదా టైప్ చేయండి.',placeholderResponse:'మీకు కావాల్సింది టైప్ చేయండి లేదా అంశాన్ని ఎంచుకోండి.',linkScheme:'ప్రభుత్వ పథకాలను చూడండి',linkServices:'ప్రభుత్వ సేవలను చూడండి',pension:'పెన్షన్ లేదా ఆర్థిక సహాయం',health:'ఆరోగ్య సహాయం',documents:'ముఖ్యమైన పత్రాలు',work:'పని లేదా నైపుణ్యం నేర్చుకోండి',stepsScheme:['మీ వయసు, రాష్ట్రం, అవసరానికి సరిపోయే పథకాలను వెతకండి.','అర్హత, అవసరమైన పత్రాలు తెలుసుకోవడానికి పథకాన్ని తెరవండి.','దరఖాస్తు విధానం చదవండి. అర్థం కానిది ఉంటే ఇక్కడ అడగండి.'],stepsServices:['మీ అవసరాన్ని ఎంచుకుని ప్రభుత్వ సేవలను చూడండి.','మీ రాష్ట్రం లేదా శాఖకు సంబంధించిన సేవను కనుగొనండి.','కొనసాగేముందు రుసుము, పత్రాలు, అధికారిక చిరునామా తనిఖీ చేయండి.'],note:'అర్హత, నియమాలు రాష్ట్రాన్ని బట్టి మారవచ్చు. OTP, PIN, బ్యాంక్ పాస్‌వర్డ్‌ను ఎవరితోనూ పంచుకోవద్దు.',sent:'మీ ప్రశ్న',tapTopic:'మీరు ఎంచుకున్నది'},
  mr:{eyebrow:'तुमच्या भाषेत तुमची मदतनीस',title:'कशासाठी मदत\nहवी आहे?',subtitle:'बोलून किंवा लिहून सांगा. आपण एकेक पाऊल घेऊ.',micTitle:'बोलण्यासाठी टॅप करा',micHint:'तुम्ही नेहमी बोलता तसे सांगा',orType:'किंवा इथे लिहा',inputLabel:'तुमचा प्रश्न लिहा',placeholder:'उदाहरण: मला पेन्शन मिळवण्यासाठी मदत हवी',privacy:'या डेमोमध्ये तुमचा प्रश्न याच डिव्हाइसवर राहतो.',quickTitle:'किंवा एक विषय निवडा',topicPension:'पेन्शन आणि मदत',topicHealth:'आरोग्य सेवा',topicDocs:'माझी कागदपत्रे',topicWork:'काम आणि कौशल्ये',answerLabel:'पुढची पावले',officialCaption:'पुढे सरकारी वेबसाइटवर जाल.',trust:'सोपे मार्गदर्शन. सरकारी वेबसाइटचे दुवे.',moreServices:'सेवा पाहा ↗',footer:'सुरुवात करण्यासाठी तुमची सोबती',notGov:'ही सरकारी वेबसाइट नाही',listening:'ऐकत आहे… बोला',voiceUnsupported:'या ब्राउझरमध्ये आवाजाने लिहिता येत नाही. खाली टाइप करा.',noSpeech:'समजले नाही. पुन्हा प्रयत्न करा किंवा टाइप करा.',placeholderResponse:'तुमची गरज टाइप करा किंवा विषय निवडा.',linkScheme:'सरकारी योजना पाहा',linkServices:'सरकारी सेवा पाहा',pension:'पेन्शन किंवा आर्थिक मदत',health:'आरोग्य मदत',documents:'महत्त्वाची कागदपत्रे',work:'काम किंवा कौशल्य शिका',stepsScheme:['वय, राज्य आणि गरजेनुसार योजना शोधा.','योजनेसाठी पात्रता आणि आवश्यक कागदपत्रे तपासा.','अर्ज कसा करायचा ते वाचा. काही समजले नाही तर इथे विचारा.'],stepsServices:['तुमची गरज निवडून सरकारी सेवा पाहा.','तुमच्या राज्याची किंवा विभागाची सेवा शोधा.','पुढे जाण्यापूर्वी शुल्क, कागदपत्रे आणि सरकारी पत्ता तपासा.'],note:'पात्रता आणि नियम राज्यानुसार वेगळे असू शकतात. OTP, PIN किंवा बँकेचा पासवर्ड कोणालाही सांगू नका.',sent:'तुमचा प्रश्न',tapTopic:'तुम्ही निवडले'},
};
// Starter translations for the other scheduled Indian languages. Keep the main
// prompts, topic choices and next-step headings in the selected script; English
// remains the fallback for detailed guidance where the demo has no translation.
const extraCopy={
  as:{eyebrow:'আপোনাৰ ভাষাত আপোনাৰ সহায়ক',title:'কিহত সহায়\nলাগিব?',subtitle:'কওক বা লিখক। আমি ধাপে ধাপে আগবাঢ়িম।',micTitle:'ক’বলৈ টিপক',micHint:'নিজৰ ভাষাত স্বাভাৱিকভাৱে কওক',orType:'নহ’লে ইয়াত লিখক',placeholder:'উদাহৰণ: পেঞ্চন বিচাৰি সহায় লাগে',quickTitle:'নহ’লে এটা বিষয় বাছক',topicPension:'পেঞ্চন আৰু সহায়',topicHealth:'স্বাস্থ্য সেৱা',topicDocs:'মোৰ নথিপত্ৰ',topicWork:'কাম আৰু দক্ষতা',answerLabel:'আপোনাৰ পৰৱৰ্তী পদক্ষেপ',footer:'আৰম্ভ কৰিবলৈ আপোনাৰ সংগী',notGov:'এইটো চৰকাৰী ৱেবছাইট নহয়'},
  brx:{eyebrow:'नोंथांनि रावजों मदद',title:'मा मदद\nनांगौ?',subtitle:'बुंनो एबा लिरनो। जों खेब खेब मदद होगोन।',micTitle:'बुंनो थांनायखौ दब',micHint:'नोंथांनि रावजों बुं',orType:'एबा बेयाव लिर',placeholder:'जेरै: पेन्सननि मदद नांगौ',quickTitle:'एबा मोनसे बिसय सायख',topicPension:'पेन्सन आरो मदद',topicHealth:'आरोमगिरि सेवा',topicDocs:'आंनि फोरमान बिलाइ',topicWork:'खामानि आरो सोलोंनाय',answerLabel:'नोंथांनि उननि खेब',footer:'गुबै खेब मदद',notGov:'बेयो सरकारि वेबसाइट नङा'},
  doi:{eyebrow:'तुंदी भाशा च मदद',title:'कुस चीजै च\nमदद चाहिदी?',subtitle:'बोलो जां लिखो। अस इक-इक कदम चलगे।',micTitle:'बोलने आस्तै दबाओ',micHint:'अपनी भाशा च बोलो',orType:'जां इत्थै लिखो',placeholder:'मिसाल: पेंशन लेई मदद चाहीदी',quickTitle:'जां इक विषय चुनो',topicPension:'पेंशन ते मदद',topicHealth:'सेहत सेवा',topicDocs:'मेरे दस्तावेज़',topicWork:'कम्म ते हुनर',answerLabel:'अगले कदम',footer:'शुरुआत च तुंदी साथी',notGov:'एह सरकारी वेबसाइट नेईं ऐ'},
  gu:{eyebrow:'તમારી ભાષામાં તમારી મદદગાર',title:'શામાં મદદ\nજોઈએ છે?',subtitle:'બોલો અથવા લખો. આપણે એક પછી એક પગલું લઈશું.',micTitle:'બોલવા માટે ટૅપ કરો',micHint:'તમારી ભાષામાં સહજ રીતે બોલો',orType:'અથવા અહીં લખો',placeholder:'ઉદાહરણ: પેન્શન મેળવવામાં મદદ જોઈએ',quickTitle:'અથવા વિષય પસંદ કરો',topicPension:'પેન્શન અને સહાય',topicHealth:'આરોગ્ય સેવા',topicDocs:'મારા દસ્તાવેજો',topicWork:'કામ અને કૌશલ્ય',answerLabel:'આગળનાં પગલાં',footer:'શરૂઆત માટે તમારી સાથી',notGov:'આ સરકારી વેબસાઇટ નથી'},
  kn:{eyebrow:'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ನಿಮ್ಮ ಸಹಾಯಕಿ',title:'ಯಾವ ವಿಷಯದಲ್ಲಿ\nಸಹಾಯ ಬೇಕು?',subtitle:'ಮಾತನಾಡಿ ಅಥವಾ ಬರೆಯಿರಿ. ಒಂದೊಂದೇ ಹೆಜ್ಜೆ ಮುಂದೆ ಹೋಗೋಣ.',micTitle:'ಮಾತನಾಡಲು ಒತ್ತಿ',micHint:'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಸಹಜವಾಗಿ ಮಾತನಾಡಿ',orType:'ಅಥವಾ ಇಲ್ಲಿ ಬರೆಯಿರಿ',placeholder:'ಉದಾಹರಣೆ: ಪಿಂಚಣಿ ಪಡೆಯಲು ಸಹಾಯ ಬೇಕು',quickTitle:'ಅಥವಾ ವಿಷಯ ಆಯ್ಕೆಮಾಡಿ',topicPension:'ಪಿಂಚಣಿ ಮತ್ತು ನೆರವು',topicHealth:'ಆರೋಗ್ಯ ಸೇವೆ',topicDocs:'ನನ್ನ ದಾಖಲೆಗಳು',topicWork:'ಕೆಲಸ ಮತ್ತು ಕೌಶಲ್ಯ',answerLabel:'ಮುಂದಿನ ಹಂತಗಳು',footer:'ಆರಂಭಿಸಲು ನಿಮ್ಮ ಜೊತೆಗಾರ್ತಿ',notGov:'ಇದು ಸರ್ಕಾರಿ ವೆಬ್‌ಸೈಟ್ ಅಲ್ಲ'},
  ks:{eyebrow:'تُہندِ زَبانہٕ مَنٛز مدد',title:'کِتھ پٲٹھۍ مدد\nضرورت چھِ?',subtitle:'وُچھِو یا لیکھو۔ اَسۍ قدم بہ قدم گژھَو۔',micTitle:'وُنُن خٲطرٕ ٹَپ کٔرِو',micHint:'پنٛنہِ زَبانہٕ مَنٛز وُچھِو',orType:'یا یَتھ لیکھو',placeholder:'مثال: پنشن خٲطرٕ مدد چھِٚیہ',quickTitle:'یا اَکھ موضوع ژٲریو',topicPension:'پنشن تہٕ مدد',topicHealth:'صحت سروس',topicDocs:'مےٚ دستاویز',topicWork:'کام تہٕ ہُنر',answerLabel:'اَگلے قدم',footer:'شروعات خٲطرٕ مددگار',notGov:'یہِ سرکاری ویب سائٹ چھِ نَہ'},
  kok:{eyebrow:'तुमच्या भाशेंत तुमची मदत',title:'खंयच्या कामाक\nमदत जाय?',subtitle:'उलोवचें वा बरयचें. एकेक पावलान वचूंया.',micTitle:'उलोवपाक टॅप करात',micHint:'तुमच्या भाशेंत उलोवचें',orType:'वा हांगा बरयात',placeholder:'उदाहरण: पेन्शनाक मदत जाय',quickTitle:'वा विशय वेंचात',topicPension:'पेन्शन आनी आदार',topicHealth:'आरोग्य सेवा',topicDocs:'म्हजीं कागदां',topicWork:'काम आनी कौशल्य',answerLabel:'फुडलीं पावलां',footer:'सुरवातीक तुमची सोबती',notGov:'हें सरकारी संकेतथळ न्हय'},
  mai:{eyebrow:'अहाँक भाषामे अहाँक सहायक',title:'कोन काजमे\nमदति चाही?',subtitle:'बोलू वा लिखू। हम एक-एकटा कदम संग चलब।',micTitle:'बजबाक लेल छूबू',micHint:'अपन भाषामे सहज रूपेँ बाजू',orType:'अथवा एतय लिखू',placeholder:'जेना: पेंशन लेल मदति चाही',quickTitle:'अथवा विषय चुनू',topicPension:'पेंशन आ सहायता',topicHealth:'स्वास्थ्य सेवा',topicDocs:'हमर कागजात',topicWork:'काज आ कौशल',answerLabel:'आगू के कदम',footer:'शुरुआत लेल अहाँक संगी',notGov:'ई सरकारी वेबसाइट नहि अछि'},
  ml:{eyebrow:'നിങ്ങളുടെ ഭാഷയിൽ സഹായം',title:'എന്തിലാണ്\nസഹായം വേണ്ടത്?',subtitle:'പറയുകയോ എഴുതുകയോ ചെയ്യൂ. ഓരോ ചുവടും ഒരുമിച്ച് നോക്കാം.',micTitle:'സംസാരിക്കാൻ തൊടുക',micHint:'നിങ്ങളുടെ ഭാഷയിൽ സ്വാഭാവികമായി പറയൂ',orType:'അല്ലെങ്കിൽ ഇവിടെ എഴുതൂ',placeholder:'ഉദാഹരണം: പെൻഷൻ ലഭിക്കാൻ സഹായം വേണം',quickTitle:'അല്ലെങ്കിൽ വിഷയം തിരഞ്ഞെടുക്കൂ',topicPension:'പെൻഷനും സഹായവും',topicHealth:'ആരോഗ്യ സേവനം',topicDocs:'എന്റെ രേഖകൾ',topicWork:'ജോലിയും നൈപുണ്യവും',answerLabel:'അടുത്ത ഘട്ടങ്ങൾ',footer:'തുടങ്ങാൻ നിങ്ങളുടെ കൂട്ടുകാരി',notGov:'ഇത് സർക്കാർ വെബ്സൈറ്റ് അല്ല'},
  mni:{eyebrow:'ꯅꯪꯒꯤ ꯂꯣꯟꯗ ꯃꯇꯦꯡ',title:'ꯀꯔꯝꯕ ꯃꯇꯦꯡ\nꯄꯥꯝꯕꯒꯦ?',subtitle:'ꯋꯥꯍꯪ ꯄꯤꯌꯨ ꯅꯠꯔꯒ ꯏꯌꯨ। ꯑꯃꯝꯕ ꯑꯃꯝꯕ ꯂꯝꯖꯤꯡꯒꯅꯤ।',micTitle:'ꯋꯥꯍꯪ ꯄꯤꯅꯕ ꯇꯞ ꯇꯧ',micHint:'ꯅꯪꯒꯤ ꯂꯣꯟꯗ ꯋꯥꯍꯪ ꯄꯤꯌꯨ',orType:'ꯅꯠꯔꯒ ꯃꯐꯝꯁꯤꯗ ꯏꯌꯨ',placeholder:'ꯃꯁꯥꯜ: ꯄꯦꯟꯁꯟꯒꯤ ꯃꯇꯦꯡ ꯄꯥꯝꯃꯤ',quickTitle:'ꯅꯠꯔꯒ ꯃꯔꯣꯝ ꯑꯃ ꯈꯜꯂꯨ',topicPension:'ꯄꯦꯟꯁꯟ ꯑꯃꯁꯨꯡ ꯃꯇꯦꯡ',topicHealth:'ꯑꯔꯣꯒꯌ ꯁꯔꯚꯤꯁ',topicDocs:'ꯑꯩꯒꯤ ꯄꯥꯎꯖꯦꯜ',topicWork:'ꯊꯕꯛ ꯑꯃꯁꯨꯡ ꯁꯛꯇꯝ',answerLabel:'ꯃꯊꯪꯒꯤ ꯂꯝꯖꯤꯡ',footer:'ꯍꯧꯅꯕ ꯅꯪꯒꯤ ꯃꯇꯦꯡ',notGov:'ꯃꯁꯤ ꯁꯔꯀꯥꯔꯒꯤ ꯋꯦꯕꯁꯥꯏꯠ ꯅꯠꯇꯦ'},
  ne:{eyebrow:'तपाईंको भाषामा तपाईंको सहयोगी',title:'के कुरामा\nसहयोग चाहिन्छ?',subtitle:'भन्नुहोस् वा लेख्नुहोस्। हामी एकएक पाइला सँगै चाल्नेछौँ।',micTitle:'बोल्न थिच्नुहोस्',micHint:'आफ्नो भाषामा स्वाभाविक रूपमा भन्नुहोस्',orType:'वा यहाँ लेख्नुहोस्',placeholder:'उदाहरण: पेन्सन पाउन सहयोग चाहियो',quickTitle:'वा एउटा विषय छान्नुहोस्',topicPension:'पेन्सन र सहयोग',topicHealth:'स्वास्थ्य सेवा',topicDocs:'मेरा कागजात',topicWork:'काम र सीप',answerLabel:'अबका चरणहरू',footer:'सुरु गर्न तपाईंको साथी',notGov:'यो सरकारी वेबसाइट होइन'},
  or:{eyebrow:'ଆପଣଙ୍କ ଭାଷାରେ ସହାୟତା',title:'କେଉଁଥିରେ\nସହାୟତା ଦରକାର?',subtitle:'କୁହନ୍ତୁ କିମ୍ବା ଲେଖନ୍ତୁ। ଆମେ ଧୀରେ ଧୀରେ ଆଗେଇବା।',micTitle:'କହିବାକୁ ଟ୍ୟାପ୍ କରନ୍ତୁ',micHint:'ନିଜ ଭାଷାରେ ସ୍ୱାଭାବିକ ଭାବେ କୁହନ୍ତୁ',orType:'ନହେଲେ ଏଠାରେ ଲେଖନ୍ତୁ',placeholder:'ଉଦାହରଣ: ପେନ୍‌ସନ୍ ପାଇଁ ସହାୟତା ଦରକାର',quickTitle:'ନହେଲେ ଏକ ବିଷୟ ବାଛନ୍ତୁ',topicPension:'ପେନ୍‌ସନ୍ ଓ ସହାୟତା',topicHealth:'ସ୍ୱାସ୍ଥ୍ୟ ସେବା',topicDocs:'ମୋର ଦଲିଲ',topicWork:'କାମ ଓ ଦକ୍ଷତା',answerLabel:'ପରବର୍ତ୍ତୀ ପଦକ୍ଷେପ',footer:'ଆରମ୍ଭ ପାଇଁ ଆପଣଙ୍କ ସାଥୀ',notGov:'ଏହା ସରକାରୀ ୱେବସାଇଟ୍ ନୁହେଁ'},
  pa:{eyebrow:'ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ ਤੁਹਾਡੀ ਸਹਾਇਕ',title:'ਕਿਸ ਕੰਮ ਲਈ\nਮਦਦ ਚਾਹੀਦੀ ਹੈ?',subtitle:'ਬੋਲੋ ਜਾਂ ਲਿਖੋ। ਅਸੀਂ ਇੱਕ-ਇੱਕ ਕਦਮ ਨਾਲ ਚੱਲਾਂਗੇ।',micTitle:'ਬੋਲਣ ਲਈ ਛੂਹੋ',micHint:'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਕੁਦਰਤੀ ਤਰੀਕੇ ਨਾਲ ਬੋਲੋ',orType:'ਜਾਂ ਇੱਥੇ ਲਿਖੋ',placeholder:'ਉਦਾਹਰਨ: ਪੈਨਸ਼ਨ ਲਈ ਮਦਦ ਚਾਹੀਦੀ ਹੈ',quickTitle:'ਜਾਂ ਕੋਈ ਵਿਸ਼ਾ ਚੁਣੋ',topicPension:'ਪੈਨਸ਼ਨ ਅਤੇ ਮਦਦ',topicHealth:'ਸਿਹਤ ਸੇਵਾ',topicDocs:'ਮੇਰੇ ਦਸਤਾਵੇਜ਼',topicWork:'ਕੰਮ ਅਤੇ ਹੁਨਰ',answerLabel:'ਤੁਹਾਡੇ ਅਗਲੇ ਕਦਮ',footer:'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਤੁਹਾਡੀ ਸਾਥੀ',notGov:'ਇਹ ਸਰਕਾਰੀ ਵੈੱਬਸਾਈਟ ਨਹੀਂ ਹੈ'},
  sa:{eyebrow:'भवत्याः भाषायां सहायिका',title:'कस्मिन् विषये\nसाहाय्यं अपेक्षितम्?',subtitle:'वदतु अथवा लिखतु। वयं शनैः शनैः अग्रे गच्छामः।',micTitle:'वक्तुं स्पृशतु',micHint:'स्वभाषया सहजतया वदतु',orType:'अथवा अत्र लिखतु',placeholder:'उदाहरणम्: निवृत्तिवेतनाय साहाय्यम् इच्छामि',quickTitle:'अथवा विषयं चिनोतु',topicPension:'निवृत्तिवेतनं च सहायता',topicHealth:'आरोग्यसेवा',topicDocs:'मम प्रमाणपत्राणि',topicWork:'कार्यं च कौशलम्',answerLabel:'अग्रिमानि सोपानानि',footer:'आरम्भाय भवत्याः सहायिका',notGov:'एतत् शासकीयजालपुटं नास्ति'},
  sat:{eyebrow:'आमाक् पा़रसी रे गोड़ो',title:'ओका काज रे\nगोड़ो ला़कतीया?',subtitle:'रोड़ मे या ओल मे। आलो ञेपते ञेपते सेनोक् आ।',micTitle:'रोड़ ला़गित् दबाव मे',micHint:'आमाक् पा़रसी रे रोड़ मे',orType:'आर बाङखान नोड़े ओल मे',placeholder:'जोनोका: पेंशन ला़गित् गोड़ो ला़कतीया',quickTitle:'आर बाङखान मित् बिसय बाछाव मे',topicPension:'पेंशन आर गोड़ो',topicHealth:'सुसाथिया सेवा',topicDocs:'आमाक् कागोज को',topicWork:'का़मी आर हुनार',answerLabel:'इना़ तायोमाक् धाप को',footer:'एहोब ला़गित् आमाक् सोबति',notGov:'नोवा सोरकार रेयाक् वेबसाइट बाङकाना'},
  sd:{eyebrow:'اوهان جي ٻوليءَ ۾ مدد',title:'ڪهڙي ڪم ۾\nمدد گهرجي؟',subtitle:'ڳالهايو يا لکو. اچو ته هڪ هڪ قدم کڻون.',micTitle:'ڳالهائڻ لاءِ ٽيپ ڪريو',micHint:'پنهنجي ٻوليءَ ۾ عام نموني ڳالهايو',orType:'يا هتي لکو',placeholder:'مثال: پينشن لاءِ مدد گهرجي',quickTitle:'يا هڪ موضوع چونڊيو',topicPension:'پينشن ۽ مدد',topicHealth:'صحت جي سهولت',topicDocs:'منهنجا دستاويز',topicWork:'ڪم ۽ هنر',answerLabel:'اڳيان قدم',footer:'شروعات لاءِ اوهان جي ساٿي',notGov:'هي سرڪاري ويب سائيٽ ناهي'},
  ur:{eyebrow:'آپ کی زبان میں آپ کی مددگار',title:'کس کام میں\nمدد چاہیے؟',subtitle:'بولیں یا لکھیں۔ ہم ایک ایک قدم ساتھ چلیں گے۔',micTitle:'بولنے کے لیے دبائیں',micHint:'اپنی زبان میں عام انداز سے بولیں',orType:'یا یہاں لکھیں',placeholder:'مثال: پنشن حاصل کرنے میں مدد چاہیے',quickTitle:'یا کوئی موضوع منتخب کریں',topicPension:'پنشن اور مدد',topicHealth:'صحت کی سہولت',topicDocs:'میرے دستاویزات',topicWork:'کام اور ہنر',answerLabel:'اگلے مراحل',footer:'شروعات کے لیے آپ کی ساتھی',notGov:'یہ سرکاری ویب سائٹ نہیں ہے'}
};
Object.assign(copy,extraCopy);
const privacyByLocale={
  as:'আপোনাৰ বাৰ্তা উত্তৰৰ বাবে OpenAI-লৈ পঠিওৱা হয়। আধাৰ, OTP, PIN বা বেংকৰ তথ্য নিদিব।',
  bn:'আপনার বার্তা উত্তরের জন্য OpenAI-তে পাঠানো হয়। আধার, OTP, PIN বা ব্যাঙ্কের তথ্য দেবেন না।',
  brx:'नोंथांनि बुंथाइखौ फिननायनि थाखाय OpenAI आव दैथायो। Aadhaar, OTP, PIN एबा बैंकनि फोरमायथिहोग्रा होनो नाङा।',
  doi:'तुंदा संदेश जवाब आस्तै OpenAI गी भेजेआ जंदा ऐ। आधार, OTP, PIN जां बैंक दी जानकारी नेईं देओ।',
  en:'Your message and recent chat are sent to OpenAI for an answer. Never share Aadhaar, OTP, PIN, passwords, or bank details.',
  gu:'તમારો સંદેશ જવાબ માટે OpenAIને મોકલાય છે. આધાર, OTP, PIN કે બેંકની વિગતો ક્યારેય આપશો નહીં.',
  hi:'आपका संदेश और हाल की बातचीत जवाब के लिए OpenAI को भेजी जाती है। आधार, OTP, PIN, पासवर्ड या बैंक की जानकारी साझा न करें।',
  kn:'ನಿಮ್ಮ ಸಂದೇಶ ಮತ್ತು ಇತ್ತೀಚಿನ ಮಾತುಕತೆಯನ್ನು ಉತ್ತರಕ್ಕಾಗಿ OpenAIಗೆ ಕಳುಹಿಸಲಾಗುತ್ತದೆ. ಆಧಾರ್, OTP, PIN, ಪಾಸ್‌ವರ್ಡ್ ಅಥವಾ ಬ್ಯಾಂಕ್ ವಿವರಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಬೇಡಿ.',
  kok:'तुमचो संदेश आनी निमाणें संवाद जाप दिवपाखातीर OpenAI कडेन धाडटा. आधार, OTP, PIN, पासवर्ड वा बँकेची म्हायती दिवंक नाका.',
  mai:'अहाँक संदेश आ हालक बातचीतक जवाब लेल OpenAI लग पठाओल जाइत अछि। आधार, OTP, PIN, पासवर्ड वा बैंकक जानकारी नहि दिअ।',
  ml:'നിങ്ങളുടെ സന്ദേശവും അടുത്തിടെയുള്ള സംഭാഷണവും മറുപടിക്കായി OpenAI-ലേക്ക് അയയ്ക്കും. ആധാർ, OTP, PIN, പാസ്‌വേഡ്, ബാങ്ക് വിവരങ്ങൾ പങ്കിടരുത്.',
  mr:'तुमचा संदेश आणि अलीकडील संवाद उत्तरासाठी OpenAI कडे पाठवला जातो. आधार, OTP, PIN, पासवर्ड किंवा बँकेची माहिती देऊ नका.',
  ne:'तपाईंको सन्देश र हालको कुराकानी जवाफका लागि OpenAI मा पठाइन्छ। आधार, OTP, PIN, पासवर्ड वा बैंक विवरण नदिनुहोस्।',
  or:'ଆପଣଙ୍କ ବାର୍ତ୍ତା ଓ ସାମ୍ପ୍ରତିକ କଥାବାର୍ତ୍ତା ଉତ୍ତର ପାଇଁ OpenAIକୁ ପଠାଯାଏ। ଆଧାର, OTP, PIN, ପାସୱାର୍ଡ କିମ୍ବା ବ୍ୟାଙ୍କ ତଥ୍ୟ ଦିଅନ୍ତୁ ନାହିଁ।',
  pa:'ਤੁਹਾਡਾ ਸੁਨੇਹਾ ਅਤੇ ਹਾਲੀਆ ਗੱਲਬਾਤ ਜਵਾਬ ਲਈ OpenAI ਨੂੰ ਭੇਜੀ ਜਾਂਦੀ ਹੈ। ਆਧਾਰ, OTP, PIN, ਪਾਸਵਰਡ ਜਾਂ ਬੈਂਕ ਦੀ ਜਾਣਕਾਰੀ ਨਾ ਦਿਓ।',
  ta:'உங்கள் செய்தியும் சமீபத்திய உரையாடலும் பதிலுக்காக OpenAI-க்கு அனுப்பப்படும். ஆதார், OTP, PIN, கடவுச்சொல் அல்லது வங்கி விவரங்களைப் பகிர வேண்டாம்.',
  te:'మీ సందేశం, ఇటీవలి సంభాషణ సమాధానం కోసం OpenAIకి పంపబడతాయి. ఆధార్, OTP, PIN, పాస్‌వర్డ్ లేదా బ్యాంకు వివరాలు పంచుకోవద్దు.',
  ur:'آپ کا پیغام اور حالیہ گفتگو جواب کے لیے OpenAI کو بھیجی جاتی ہے۔ آدھار، OTP، PIN، پاس ورڈ یا بینک کی معلومات نہ دیں。',
};
for(const [locale,line] of Object.entries(privacyByLocale))if(copy[locale])copy[locale].privacy=line;
const schemeLinkByLocale={
  as:'চৰকাৰী আঁচনি বিচাৰক',brx:'सोरखारि स्किम नाय',doi:'सरकारी स्कीम दिक्खो',gu:'સરકારી યોજનાઓ જુઓ',kn:'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ನೋಡಿ',ks:'سرکاری اسکیمہ وٲچھِو',kok:'सरकारी येवजण्यो पळयात',mai:'सरकारी योजना देखू',ml:'സർക്കാർ പദ്ധതികൾ കാണുക',mni:'ꯁꯔꯀꯥꯔꯒꯤ ꯁꯤꯝꯁꯤꯡ ꯌꯦꯡꯉꯨ',ne:'सरकारी योजनाहरू हेर्नुहोस्',or:'ସରକାରୀ ଯୋଜନା ଦେଖନ୍ତୁ',pa:'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਵੇਖੋ',sa:'शासकीययोजनाः पश्यन्तु',sat:'सोरकारि स्किम को ञेल मे',sd:'سرڪاري رٿائون ڏسو',ur:'سرکاری اسکیمیں دیکھیں'
};
for(const [locale,label] of Object.entries(schemeLinkByLocale))if(copy[locale])copy[locale].linkScheme=label;
const newUiDefaults={stateLabel:'YOUR STATE / UT',brandCaption:'GOVERNMENT HELP, MADE HUMAN',safeTitle:'Keep your information safe',askLabel:'ASK DISHA',askTitle:'What kind of help are you looking for?',searchHint:'Search official sources · get an answer in your language',offlineHint:'Offline guide ready · common government services',offlinePrivacy:'Offline questions stay on this device. Never share Aadhaar, OTP, PIN, passwords, or bank details.',browseMore:'Browse all help topics',setupFile:'To get answers, start Disha and open http://127.0.0.1:4173 (not this saved file).',setupKey:'Disha is running, but its AI key is not set. Add OPENAI_API_KEY to the .env file and restart Disha.',setupServer:'Disha’s local service is not running. Start it with “npm start”, then open http://127.0.0.1:4173.',sourcesTitle:'OFFICIAL SOURCES',verifiedLabel:'Sources are checked'};
for(const locale of Object.values(copy))Object.assign(locale,newUiDefaults);
for(const locale of Object.values(copy))locale.trust='Read the scheme details here. Open an official page only if you choose.';
Object.assign(copy.hi,{brandCaption:'सरकारी मदद, आपकी भाषा में',safeTitle:'अपनी जानकारी सुरक्षित रखें',askLabel:'दिशा से पूछें',askTitle:'आपको किस मदद की तलाश है?',searchHint:'सरकारी स्रोतों में खोजेगा · आपकी भाषा में जवाब देगा',sourcesTitle:'आधिकारिक स्रोत',verifiedLabel:'स्रोत जाँचे जाते हैं'});
Object.assign(copy.hi,{offlineHint:'बिना इंटरनेट भी मदद मिलेगी · सरकारी सेवाओं के बारे में पूछें',offlinePrivacy:'बिना इंटरनेट वाले सवाल इसी डिवाइस पर रहते हैं। आधार, OTP, PIN या बैंक की जानकारी साझा न करें।',browseMore:'सभी मदद के विषय देखें',setupFile:'जवाब पाने के लिए Disha चालू करें और http://127.0.0.1:4173 खोलें। यह सेव की हुई फ़ाइल है, यहाँ जवाब नहीं मिलेंगे।',setupKey:'Disha चल रहा है, लेकिन AI key सेट नहीं है। .env फ़ाइल में OPENAI_API_KEY जोड़कर Disha फिर से शुरू करें।',setupServer:'Disha सेवा नहीं चल रही। “npm start” से शुरू करें, फिर http://127.0.0.1:4173 खोलें।'});
copy.hi.trust='योजना की जानकारी यहीं पढ़ें। सरकारी पेज आप चाहें तभी खोलें।';
copy.hi.stateLabel='आपका राज्य / केंद्र शासित प्रदेश';
copy.hi.privacy='आपका सवाल और चुना हुआ राज्य जवाब के लिए OpenAI को भेजा जाता है। आधार, OTP, PIN या बैंक की जानकारी साझा न करें।';
Object.assign(copy.bn,{brandCaption:'সরকারি সহায়তা, আপনার ভাষায়',safeTitle:'আপনার তথ্য নিরাপদ রাখুন',askLabel:'দিশাকে জিজ্ঞাসা করুন',askTitle:'আপনি কী ধরনের সাহায্য খুঁজছেন?',searchHint:'সরকারি সূত্রে খুঁজবে · আপনার ভাষায় উত্তর দেবে',sourcesTitle:'সরকারি সূত্র',verifiedLabel:'সূত্র যাচাই করা হয়'});
copy.bn.trust='প্রকল্পের বিবরণ এখানেই পড়ুন। সরকারি পাতা খুলবেন শুধু আপনি চাইলে।';
Object.assign(copy.ta,{brandCaption:'அரசு உதவி, உங்கள் மொழியில்',safeTitle:'உங்கள் தகவலைப் பாதுகாப்பாக வைத்திருங்கள்',askLabel:'திஷாவிடம் கேளுங்கள்',askTitle:'எந்த உதவியைத் தேடுகிறீர்கள்?',searchHint:'அரசு ஆதாரங்களில் தேடி · உங்கள் மொழியில் பதிலளிக்கும்',sourcesTitle:'அதிகாரப்பூர்வ ஆதாரங்கள்',verifiedLabel:'ஆதாரங்கள் சரிபார்க்கப்படும்'});
copy.ta.trust='திட்ட விவரங்களை இங்கே படிக்கவும். நீங்கள் விரும்பினால் மட்டுமே அரசு பக்கத்தைத் திறக்கவும்.';
copy.ta.stateLabel='உங்கள் மாநிலம் / யூனியன் பிரதேசம்';
copy.ta.privacy='உங்கள் கேள்வியும் தேர்ந்தெடுத்த மாநிலமும் பதிலுக்காக OpenAI-க்கு அனுப்பப்படும். ஆதார் எண், OTP, PIN அல்லது வங்கி விவரங்களைப் பகிர வேண்டாம்.';
Object.assign(copy.te,{brandCaption:'ప్రభుత్వ సహాయం, మీ భాషలో',safeTitle:'మీ సమాచారాన్ని సురక్షితంగా ఉంచండి',askLabel:'దిశను అడగండి',askTitle:'మీరు ఎలాంటి సహాయం వెతుకుతున్నారు?',searchHint:'ప్రభుత్వ మూలాల్లో వెతికి · మీ భాషలో సమాధానం ఇస్తుంది',sourcesTitle:'అధికారిక మూలాలు',verifiedLabel:'మూలాలు తనిఖీ చేయబడతాయి'});
copy.te.trust='పథకం వివరాలను ఇక్కడ చదవండి. మీరు కోరితేనే అధికారిక పేజీని తెరవండి.';
Object.assign(copy.mr,{brandCaption:'सरकारी मदत, तुमच्या भाषेत',safeTitle:'तुमची माहिती सुरक्षित ठेवा',askLabel:'दिशाला विचारा',askTitle:'तुम्हाला कोणत्या मदतीची गरज आहे?',searchHint:'सरकारी स्रोत शोधेल · तुमच्या भाषेत उत्तर देईल',sourcesTitle:'अधिकृत स्रोत',verifiedLabel:'स्रोत तपासले जातात'});
copy.mr.trust='योजनेची माहिती इथे वाचा. तुम्हाला हवे असेल तेव्हाच अधिकृत पान उघडा.';
for(const locale of Object.values(extraCopy)){
  locale.pension=locale.topicPension;locale.health=locale.topicHealth;
  locale.documents=locale.topicDocs;locale.work=locale.topicWork;
}
const language=document.querySelector('#language'), stateSelector=document.querySelector('#state'), q=document.querySelector('#question'), answer=document.querySelector('#answer'), mic=document.querySelector('#mic'), micTitle=document.querySelector('#mic-title'), micHint=document.querySelector('#mic-hint'), toast=document.querySelector('#toast');let current='en', toastTimer, chatHistory=[], busy=false;
function t(k){return (copy[current]||copy.hi)[k]||copy.en[k]||k}
function applyLanguage(code){current=copy[code]?code:'en';document.documentElement.lang=current;document.documentElement.dir=['ks','sd','ur'].includes(current)?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));document.querySelector('#mic-hint').textContent=t('micHint');document.querySelectorAll('.directory-topic').forEach((button,index)=>button.textContent=current==='hi'?directoryTopics[index].hi:directoryTopics[index].en);q.value='';answer.hidden=true;chatHistory=[];checkReadiness();}
language.addEventListener('change',e=>applyLanguage(e.target.value));
async function checkReadiness(){
  const hint=document.querySelector('#search-hint'),dot=document.querySelector('#status-dot');
  const privacy=document.querySelector('[data-i18n="privacy"]');
  if(location.protocol==='file:'){hint.textContent=t('offlineHint');privacy.textContent=t('offlinePrivacy');dot.classList.remove('needs-setup');return false}
  try{const response=await fetch('/api/health',{cache:'no-store'});if(!response.ok)throw new Error('offline');const health=await response.json();
    if(!health.ready){hint.textContent=t('offlineHint');privacy.textContent=t('offlinePrivacy');dot.classList.remove('needs-setup');return false}
    hint.textContent=t('searchHint');privacy.textContent=t('privacy');dot.classList.remove('needs-setup');return true;
  }catch{hint.textContent=t('offlineHint');privacy.textContent=t('offlinePrivacy');dot.classList.remove('needs-setup');return false}
}
function notify(text){toast.textContent=text;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3100)}
function clearGuide(){document.querySelector('#answer-summary').textContent='';document.querySelector('#follow-up').hidden=true;document.querySelector('#follow-up').textContent='';document.querySelector('#scheme-list').replaceChildren();document.querySelector('#steps').replaceChildren();document.querySelector('#answer-note').textContent='';document.querySelector('#source-list').replaceChildren();document.querySelector('#sources-wrap').hidden=true;document.querySelector('#official-link').hidden=true;}
function renderGuide(guide){
  document.querySelector('#answer-title').textContent=guide.intent_summary||'Disha found a possible path';
  document.querySelector('#answer-summary').textContent=guide.reply||'';
  const question=document.querySelector('#follow-up');question.hidden=!guide.follow_up_question;question.textContent=guide.follow_up_question||'';
  const cards=document.querySelector('#scheme-list');cards.replaceChildren();
  for(const scheme of guide.schemes||[]){
    const card=document.createElement('article');card.className='scheme-card';
    const title=document.createElement('h3');title.textContent=scheme.name;card.append(title);
    for(const value of [scheme.fit_reason,scheme.benefit,scheme.eligibility_to_check,scheme.how_to_start]){
      if(!value)continue;const row=document.createElement('p');row.className='scheme-detail';row.textContent=value;card.append(row);
    }
    const url=officialLink(scheme.official_url);if(url){const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener';link.className='scheme-apply';link.textContent=scheme.name+' ↗';card.append(link)}
    cards.append(card);
  }
  const steps=document.querySelector('#steps');steps.replaceChildren(...(guide.next_steps||[]).map(line=>{const li=document.createElement('li');li.textContent=line;return li}));
  document.querySelector('#answer-note').textContent=guide.safety_note||'';
  const sourceList=document.querySelector('#source-list'), sources=(guide.sources||[]).map(item=>({...item,url:officialLink(item.url)})).filter(item=>item.url);
  sourceList.replaceChildren(...sources.map(source=>{const a=document.createElement('a');a.href=source.url;a.target='_blank';a.rel='noopener';a.textContent=source.title||'Official government source ↗';return a}));
  document.querySelector('#sources-wrap').hidden=!sources.length;
  const fallback=document.querySelector('#official-link');fallback.hidden=Boolean((guide.schemes||[]).length||guide.follow_up_question);fallback.href='https://www.myscheme.gov.in/';document.querySelector('#link-label').textContent=t('linkScheme');
}
function officialLink(value){try{const u=new URL(value);return u.protocol==='https:'&&(/(^|\.)gov\.in$|(^|\.)nic\.in$/i).test(u.hostname)?u.href:null}catch{return null}}
const offlineDirectory=[
  {id:'birth',en:'Birth registration & certificates',hi:'जन्म पंजीकरण और प्रमाणपत्र',prompt:'birth registration certificate',match:/\b(birth|born|birth certificate|birth registration)\b|जन्म|जन्म प्रमाण पत्र|जन्म पंजीकरण/i,reply:['For a birth certificate, contact the local Registrar of Births and Deaths or your municipal office. Online registration is available only in some states and areas, so choose your state on the official Civil Registration System portal.','जन्म प्रमाणपत्र के लिए स्थानीय जन्म-मृत्यु रजिस्ट्रार या नगर निकाय से संपर्क करें। ऑनलाइन सुविधा कुछ राज्यों और क्षेत्रों में ही उपलब्ध है; आधिकारिक नागरिक पंजीकरण पोर्टल पर अपना राज्य चुनें।'],steps:[['Tell me your state or district for the correct office.','अपने राज्य या ज़िले का नाम बताएं ताकि सही कार्यालय खोज सकें।'],['Ask the local registrar or municipal office how to register the birth.','स्थानीय रजिस्ट्रार या नगर कार्यालय से पंजीकरण का तरीका पूछें।'],['Use only the official government portal; requirements and time limits can vary.','केवल सरकारी पोर्टल इस्तेमाल करें; दस्तावेज़ और समय-सीमा अलग हो सकती है।']],url:'https://dc.crsorgi.gov.in/crs/ReportEvent/ReportBirth',source:'Civil Registration System — Government of India'},
  {id:'identity',en:'Identity cards & worker registration',hi:'पहचान पत्र और श्रमिक पंजीकरण',prompt:'Aadhaar identity card or e-Shram registration',match:/\b(aadhaar|identity card|national id|social security|e.?shram|worker registration)\b|आधार|पहचान पत्र|श्रमिक पंजीकरण/i,reply:['India does not use a US-style Social Security Number. For identity services, use UIDAI’s Aadhaar information; unorganised workers can check e-Shram. Do not enter your Aadhaar number, OTP, or PIN here.','भारत में अमेरिका जैसा Social Security Number नहीं है। पहचान संबंधी सेवाओं के लिए UIDAI की आधार जानकारी देखें; असंगठित कामगार e-Shram देख सकते हैं। अपना आधार नंबर, OTP या PIN यहाँ न लिखें।'],steps:[['Choose whether you need Aadhaar help or worker registration.','बताएं कि आपको आधार सहायता चाहिए या श्रमिक पंजीकरण।'],['For Aadhaar, contact an authorized Aadhaar centre listed by UIDAI.','आधार के लिए UIDAI द्वारा सूचीबद्ध अधिकृत केंद्र जाएं।'],['Never share an OTP or full identity number in chat or with an agent.','चैट या एजेंट के साथ OTP या पूरा पहचान नंबर साझा न करें।']],url:'https://uidai.gov.in/',source:'UIDAI — Government of India',extra:['e-Shram — Government of India','https://eshram.gov.in/']},
  {id:'passport',en:'Passport & travel documents',hi:'पासपोर्ट और यात्रा दस्तावेज़',prompt:'apply for a passport',match:/\b(passport|travel document|visa)\b|पासपोर्ट|यात्रा दस्तावेज़/i,reply:['Apply for an Indian passport through Passport Seva, the Ministry of External Affairs portal. The usual process is to register, submit the application, pay the applicable fee, book an appointment, and visit a Passport Seva Kendra. Check the current document list and fee there.','भारतीय पासपोर्ट के लिए विदेश मंत्रालय के Passport Seva पोर्टल का उपयोग करें। आम तौर पर पंजीकरण, आवेदन, लागू शुल्क, अपॉइंटमेंट और पासपोर्ट सेवा केंद्र जाना होता है। मौजूदा दस्तावेज़ और शुल्क वहीं जांचें।'],steps:[['Use the official Passport Seva website only.','केवल आधिकारिक Passport Seva वेबसाइट इस्तेमाल करें।'],['Read the fresh-passport or re-issue guide that matches your need.','अपनी ज़रूरत के अनुसार नया पासपोर्ट या नवीनीकरण गाइड चुनें।'],['Check fees and required documents before paying or booking.','भुगतान या अपॉइंटमेंट से पहले शुल्क और दस्तावेज़ जांचें।']],url:'https://www.passportindia.gov.in/psp/GettingStarted',source:'Passport Seva — Ministry of External Affairs'},
  {id:'death',en:'Death registration & legal next steps',hi:'मृत्यु पंजीकरण और कानूनी अगले कदम',prompt:'death certificate and legal heir help',match:/\b(death certificate|death registration|estate settlement|inheritance|legal heir|succession)\b|मृत्यु प्रमाण पत्र|मृत्यु पंजीकरण|उत्तराधिकार|वारिस/i,reply:['A death must be registered with the local Registrar of Births and Deaths or municipal office. Estate, inheritance, and legal-heir steps depend on the situation and local rules; free legal aid is available through NALSA.','मृत्यु का पंजीकरण स्थानीय जन्म-मृत्यु रजिस्ट्रार या नगर निकाय में कराएं। संपत्ति, उत्तराधिकार और कानूनी वारिस की प्रक्रिया स्थिति व नियमों पर निर्भर करती है; NALSA से निःशुल्क कानूनी सहायता मिल सकती है।'],steps:[['Ask the local registrar how to register the death and request a certificate.','स्थानीय रजिस्ट्रार से मृत्यु पंजीकरण और प्रमाणपत्र की प्रक्रिया पूछें।'],['For property or inheritance questions, contact your District Legal Services Authority.','संपत्ति या उत्तराधिकार के लिए ज़िला विधिक सेवा प्राधिकरण से संपर्क करें।'],['Do not share account numbers, passwords, or OTPs with anyone.','किसी के साथ खाता नंबर, पासवर्ड या OTP साझा न करें।']],url:'https://dc.crsorgi.gov.in/crs/ReportEvent/ReportBirth',source:'Civil Registration System — Government of India',extra:['NALSA — Free legal aid','https://nalsa.gov.in/promoting-inclusive-legal-system/']},
  {id:'insurance',en:'Public health insurance',hi:'सरकारी स्वास्थ्य बीमा',prompt:'government health insurance Ayushman Bharat',match:/\b(health insurance|medical insurance|ayushman|pm.?jay|health cover|hospital cover)\b|स्वास्थ्य बीमा|आयुष्मान|इलाज का खर्च/i,reply:['Ayushman Bharat PM-JAY provides health-cover benefits to eligible families. Check whether your family is eligible through the official beneficiary portal or ask an Ayushman Mitra at a listed hospital. The guide cannot confirm eligibility.','आयुष्मान भारत PM-JAY पात्र परिवारों को स्वास्थ्य कवर देता है। आधिकारिक लाभार्थी पोर्टल पर जांचें या सूचीबद्ध अस्पताल के आयुष्मान मित्र से पूछें। यह गाइड पात्रता की पुष्टि नहीं कर सकती।'],steps:[['Check eligibility on the official beneficiary portal.','आधिकारिक लाभार्थी पोर्टल पर पात्रता जांचें।'],['Ask an Ayushman Mitra at a participating hospital for help.','सूचीबद्ध अस्पताल में आयुष्मान मित्र से सहायता लें।'],['Never pay an agent to “guarantee” eligibility.','पात्रता की “गारंटी” देने वाले एजेंट को पैसे न दें।']],url:'https://beneficiary.nha.gov.in/',source:'National Health Authority — Government of India'},
  {id:'immunization',en:'Vaccination & immunization',hi:'टीकाकरण',prompt:'vaccination immunization for child',match:/\b(vaccin|immuni[sz]|immunization|uwin|vaccine|infectious disease|disease control|communicable disease)\w*\b|टीका|टीकाकरण|प्रतिरक्षण|संक्रामक रोग/i,reply:['Government vaccination for pregnant women and children is delivered through health facilities and tracked on U-WIN. Ask an ASHA worker or health centre about due doses, appointments, and vaccination records.','गर्भवती महिलाओं और बच्चों का सरकारी टीकाकरण स्वास्थ्य केंद्रों पर होता है और U-WIN पर दर्ज किया जाता है। बाकी टीकों, अपॉइंटमेंट और रिकॉर्ड के लिए आशा कार्यकर्ता या स्वास्थ्य केंद्र से पूछें।'],steps:[['Contact your nearest government health centre or ASHA worker.','नज़दीकी सरकारी स्वास्थ्य केंद्र या आशा कार्यकर्ता से संपर्क करें।'],['Use U-WIN to check the available citizen services.','U-WIN पर उपलब्ध नागरिक सेवाएं देखें।'],['For a medical concern or reaction, contact a qualified health professional.','स्वास्थ्य समस्या या प्रतिक्रिया के लिए योग्य स्वास्थ्यकर्मी से संपर्क करें।']],url:'https://uwindashboard.mohfw.gov.in/',source:'U-WIN — Ministry of Health and Family Welfare'},
  {id:'emergency',en:'Emergency medical help',hi:'आपातकालीन चिकित्सा सहायता',prompt:'emergency ambulance medical help',match:/\b(emergency|ambulance|first responder|urgent medical|medical emergency)\b|आपातकाल|एम्बुलेंस|तुरंत चिकित्सा/i,reply:['If someone is in immediate danger or needs urgent medical help, call India’s emergency number 112 now. This is for emergencies.','अगर कोई तत्काल खतरे में है या तुरंत चिकित्सा सहायता चाहिए, अभी भारत के आपातकालीन नंबर 112 पर कॉल करें। यह आपात स्थिति के लिए है।'],steps:[['Call 112 for urgent police, fire, or medical assistance.','तत्काल पुलिस, अग्निशमन या चिकित्सा सहायता के लिए 112 पर कॉल करें।'],['Share your location and the type of emergency with the responder.','सहायता दल को अपना स्थान और आपात स्थिति बताएं।']],url:'https://112.gov.in/',source:'Emergency Response Support System — Government of India'},
  {id:'schools',en:'Government schools & school education',hi:'सरकारी स्कूल और शिक्षा',prompt:'government school admission for my child',match:/\b(school|primary education|secondary education|school admission|government school)\b|स्कूल|विद्यालय|प्राथमिक शिक्षा|माध्यमिक शिक्षा/i,reply:['For a government school, ask the nearest school or your block/district education office about admission, age rules, and required documents. School services and procedures can differ by state.','सरकारी स्कूल में प्रवेश के लिए नज़दीकी स्कूल या ब्लॉक/ज़िला शिक्षा कार्यालय से आयु नियम और दस्तावेज़ पूछें। प्रवेश की प्रक्रिया राज्य के अनुसार बदल सकती है।'],steps:[['Tell me your state and the child’s class to narrow down the right office.','सही कार्यालय बताने के लिए राज्य और कक्षा बताएं।'],['Contact the nearest government school or district education office.','नज़दीकी सरकारी स्कूल या ज़िला शिक्षा कार्यालय से संपर्क करें।'],['Ask about admission dates, age requirements, and local documents.','प्रवेश की तारीख, आयु और स्थानीय दस्तावेज़ पूछें।']],url:'https://samagra.education.gov.in/',source:'Samagra Shiksha — Department of School Education'},
  {id:'highereducation',en:'College scholarships & vocational training',hi:'कॉलेज छात्रवृत्ति और कौशल प्रशिक्षण',prompt:'scholarship or skill training for college',match:/\b(higher education|college scholarship|scholarship|vocational|skill training|iti|training course)\b|छात्रवृत्ति|कॉलेज|उच्च शिक्षा|कौशल प्रशिक्षण|आईटीआई/i,reply:['For scholarships, look at the National Scholarship Portal and check each scheme’s eligibility and dates. For vocational courses and training centres, Skill India Digital Hub lists options. Availability and fees vary by course and state.','छात्रवृत्ति के लिए National Scholarship Portal पर योजनाएं और उनकी पात्रता व तारीखें जांचें। व्यावसायिक कोर्स और प्रशिक्षण केंद्रों के लिए Skill India Digital Hub देखें। कोर्स व राज्य के अनुसार उपलब्धता और शुल्क बदलते हैं।'],steps:[['Search the National Scholarship Portal for the current academic year.','मौजूदा शैक्षणिक वर्ष के लिए National Scholarship Portal पर खोजें।'],['Search Skill India Digital Hub for a course or nearby centre.','कोर्स या नज़दीकी केंद्र के लिए Skill India Digital Hub देखें।'],['Confirm eligibility, fees, and dates with the official provider.','पात्रता, शुल्क और तारीखें आधिकारिक संस्था से पक्का करें।']],url:'https://scholarships.gov.in/',source:'National Scholarship Portal — Government of India',extra:['Skill India Digital Hub','https://www.skillindiadigital.gov.in/']},
  {id:'library',en:'Public libraries & digital literacy',hi:'सरकारी पुस्तकालय और डिजिटल साक्षरता',prompt:'public library or learn digital skills',match:/\b(library|public library|digital literacy|computer class|computer training|learn computer)\b|पुस्तकालय|डिजिटल साक्षरता|कंप्यूटर सीखना/i,reply:['Public libraries and digital-learning centres are usually managed locally. Ask your Gram Panchayat, municipality, or district library about a nearby centre, opening hours, and classes. The Ministry of Culture shares information about public-library initiatives.','सार्वजनिक पुस्तकालय और डिजिटल शिक्षा केंद्र आम तौर पर स्थानीय स्तर पर चलते हैं। नज़दीकी केंद्र, समय और कक्षाओं के लिए ग्राम पंचायत, नगर निकाय या ज़िला पुस्तकालय से पूछें। संस्कृति मंत्रालय सार्वजनिक पुस्तकालयों की जानकारी देता है।'],steps:[['Tell me your village, town, or district to look for local options.','नज़दीकी विकल्प खोजने के लिए गांव, शहर या ज़िला बताएं।'],['Ask your Panchayat or municipal office about the nearest library or digital centre.','नज़दीकी पुस्तकालय या डिजिटल केंद्र के लिए पंचायत या नगर कार्यालय से पूछें।'],['Check opening hours and whether classes are free before visiting.','जाने से पहले समय और कक्षाओं का शुल्क पूछें।']],url:'https://culture.gov.in/national-mission-libraries',source:'National Mission on Libraries — Ministry of Culture',extra:['Common Services Centres','https://csc.gov.in/']},
  {id:'police',en:'Police help & reporting a crime',hi:'पुलिस सहायता और शिकायत',prompt:'contact police or report a crime',match:/\b(police|law enforcement|community policing|report a crime|cyber crime|cyber fraud)\b|पुलिस|अपराध की शिकायत|साइबर अपराध/i,reply:['If there is immediate danger, call 112. For other matters, contact your nearest police station or your state police website. For online financial cyber-fraud, call 1930 quickly and report at the official National Cyber Crime portal.','तत्काल खतरे में 112 पर कॉल करें। अन्य मामलों में नज़दीकी थाने या राज्य पुलिस वेबसाइट से संपर्क करें। ऑनलाइन वित्तीय साइबर धोखाधड़ी के लिए जल्द 1930 पर कॉल करें और सरकारी साइबर अपराध पोर्टल पर शिकायत करें।'],steps:[['For an emergency, call 112.','आपात स्थिति में 112 पर कॉल करें।'],['For online financial fraud, call 1930 and use the National Cyber Crime portal.','ऑनलाइन वित्तीय धोखाधड़ी में 1930 पर कॉल करें और सरकारी साइबर अपराध पोर्टल इस्तेमाल करें।'],['Never share an OTP, PIN, or password with a caller.','कॉल करने वाले को OTP, PIN या पासवर्ड न बताएं।']],url:'https://112.gov.in/',source:'Emergency Response Support System — Government of India',extra:['National Cyber Crime Reporting Portal','https://cybercrime.gov.in/']},
  {id:'fire',en:'Fire & rescue services',hi:'अग्निशमन और बचाव सेवा',prompt:'fire or rescue emergency',match:/\b(fire|fire brigade|rescue service|fire rescue)\b|आग|दमकल|अग्निशमन|बचाव सेवा/i,reply:['If there is a fire or someone needs urgent rescue, move to a safe place and call 112. India’s emergency response system connects requests for police, fire, and medical help.','आग लगने या तुरंत बचाव की ज़रूरत पर सुरक्षित जगह जाएं और 112 पर कॉल करें। भारत की आपातकालीन सेवा पुलिस, अग्निशमन और चिकित्सा सहायता से जोड़ती है।'],steps:[['Move away from smoke and danger if it is safe to do so.','अगर सुरक्षित हो तो धुएं और खतरे से दूर जाएं।'],['Call 112 and describe the location and emergency.','112 पर कॉल करके स्थान और आपात स्थिति बताएं।']],url:'https://112.gov.in/',source:'Emergency Response Support System — Government of India'},
  {id:'legal',en:'Courts & free legal aid',hi:'अदालत और निःशुल्क कानूनी सहायता',prompt:'free legal aid or court help',match:/\b(legal aid|free lawyer|court|judicial|judge|lawyer|estate|inheritance|succession)\b|कानूनी सहायता|मुफ्त वकील|अदालत|न्यायालय|उत्तराधिकार/i,reply:['Women can seek free legal aid through NALSA or their District Legal Services Authority. Call the NALSA toll-free helpline 15100 or visit the district court legal-services office. For case status, use the official eCourts service.','महिलाएं NALSA या ज़िला विधिक सेवा प्राधिकरण से निःशुल्क कानूनी सहायता मांग सकती हैं। NALSA के टोल-फ्री नंबर 15100 पर कॉल करें या ज़िला अदालत के विधिक सेवा कार्यालय जाएं। केस की स्थिति के लिए सरकारी eCourts सेवा देखें।'],steps:[['Call NALSA at 15100 or visit your District Legal Services Authority.','NALSA 15100 पर कॉल करें या ज़िला विधिक सेवा प्राधिकरण जाएं।'],['For a case-status search, use the official eCourts portal.','केस की स्थिति के लिए सरकारी eCourts पोर्टल इस्तेमाल करें।'],['Do not post private case papers or personal details in this chat.','निजी केस कागज़ या व्यक्तिगत जानकारी यहाँ न भेजें।']],url:'https://nalsa.gov.in/promoting-inclusive-legal-system/',source:'NALSA — Government of India',extra:['eCourts Services','https://ecourts.gov.in/']},
  {id:'water',en:'Water supply & sanitation',hi:'पानी की सुविधा और स्वच्छता',prompt:'tap water toilet sanitation help',match:/\b(clean water|tap water|water supply|drinking water|sanitation|toilet|sewer)\b|पीने का पानी|नल का पानी|पानी की आपूर्ति|स्वच्छता|शौचालय/i,reply:['For a broken tap-water supply or sanitation issue, contact your Gram Panchayat or urban local body first. Jal Jeevan Mission and Swachh Bharat Mission explain the national programmes; local delivery and complaints are handled by state and local offices.','नल के पानी या स्वच्छता की समस्या के लिए पहले ग्राम पंचायत या नगर निकाय से संपर्क करें। जल जीवन मिशन और स्वच्छ भारत मिशन राष्ट्रीय कार्यक्रमों की जानकारी देते हैं; स्थानीय सेवा व शिकायत राज्य/स्थानीय कार्यालय देखते हैं।'],steps:[['Tell me your state and village/town.','अपना राज्य और गांव/शहर बताएं।'],['Report a broken connection or sanitation issue to your Panchayat or municipal office.','खराब कनेक्शन या स्वच्छता समस्या पंचायत या नगर कार्यालय में बताएं।'],['Use the official mission pages to learn about the programme.','कार्यक्रम की जानकारी के लिए सरकारी मिशन पेज देखें।']],url:'https://jaljeevanmission.gov.in/',source:'Jal Jeevan Mission — Government of India',extra:['Swachh Bharat Mission (Gramin)','https://swachhbharatmission.ddws.gov.in/']},
  {id:'transport',en:'Public transport & trains',hi:'सरकारी बस और रेल सेवा',prompt:'public transport bus or train',match:/\b(public transport|public transportation|bus route|government bus|train ticket|railway|subway|metro)\b|बस सेवा|रेल|ट्रेन|मेट्रो|सार्वजनिक परिवहन/i,reply:['Bus and metro services are run by state or city transport agencies, so routes and fares depend on where you live. For Indian Railways information, use the official railways portal. Tell me your city or state for more specific guidance.','बस और मेट्रो सेवाएं राज्य या शहर की परिवहन संस्था चलाती है; मार्ग और किराया स्थान के अनुसार बदलते हैं। भारतीय रेल की जानकारी के लिए रेलवे का सरकारी पोर्टल देखें। बेहतर मार्गदर्शन के लिए शहर या राज्य बताएं।'],steps:[['Tell me your city and where you need to go.','अपना शहर और गंतव्य बताएं।'],['For bus/metro routes, check the state or city transport department.','बस/मेट्रो के लिए राज्य या शहर के परिवहन विभाग से पूछें।'],['For trains, use the official Indian Railways information portal.','ट्रेन के लिए भारतीय रेल का आधिकारिक सूचना पोर्टल इस्तेमाल करें।']],url:'https://indianrail.gov.in/',source:'Indian Railways — Government of India'},
  {id:'waste',en:'Garbage collection & recycling',hi:'कचरा उठाना और पुनर्चक्रण',prompt:'garbage collection waste recycling',match:/\b(waste|garbage|rubbish|trash|recycl|waste management|garbage collection)\b|कचरा|कूड़ा|रीसायकल|पुनर्चक्रण/i,reply:['Household waste pickup, recycling, and public-bin complaints are managed by your Gram Panchayat or municipal body. Ask about collection days, sorting rules, and the local complaint desk; these differ by area.','घर का कचरा उठाना, पुनर्चक्रण और सार्वजनिक डिब्बों की शिकायत ग्राम पंचायत या नगर निकाय देखता है। कचरा लेने के दिन, अलग करने के नियम और शिकायत कार्यालय अपने क्षेत्र में पूछें।'],steps:[['Tell me your village, town, or city.','अपना गांव, कस्बा या शहर बताएं।'],['Ask the local body about pickup days and waste sorting.','कचरा उठाने के दिन और अलग करने के तरीके स्थानीय निकाय से पूछें।'],['Report missed collection to the municipal or Panchayat complaint desk.','कचरा न उठने पर नगर या पंचायत शिकायत कार्यालय में बताएं।']],url:'https://swachhbharatmission.ddws.gov.in/',source:'Swachh Bharat Mission — Government of India'},
  {id:'jobs',en:'Jobs & employment services',hi:'नौकरी और रोज़गार सेवा',prompt:'find a job or employment support',match:/\b(unemployment|unemployed|job placement|find a job|job search|employment service|career centre)\b|बेरोज़गार|नौकरी ढूंढ|रोज़गार|काम ढूंढ/i,reply:['The National Career Service (NCS) is a Government of India job and career portal. It lists jobs, career centres, and other services. NCS says its services are free; do not pay anyone claiming to guarantee a job.','National Career Service (NCS) भारत सरकार का नौकरी और करियर पोर्टल है। यहाँ नौकरी, करियर केंद्र और दूसरी सेवाएं मिलती हैं। NCS की सेवाएं निःशुल्क हैं; नौकरी की गारंटी के नाम पर किसी को पैसे न दें।'],steps:[['Open NCS and choose jobseeker services or search jobs.','NCS खोलें और नौकरी खोजने की सेवा चुनें।'],['Tell me your city and the kind of work you want for more guidance.','और मदद के लिए अपना शहर और काम का प्रकार बताएं।'],['NCS services are free; avoid agents charging placement fees.','NCS सेवाएं मुफ्त हैं; नौकरी दिलाने के नाम पर फीस मांगने वालों से बचें।']],url:'https://www.ncs.gov.in/',source:'National Career Service — Ministry of Labour & Employment'},
  {id:'retirement',en:'Old-age pension & elderly support',hi:'वृद्धावस्था पेंशन और बुज़ुर्ग सहायता',prompt:'old age pension elderly support',match:/\b(retirement pension|old.?age pension|elderly care|senior citizen support|senior citizen pension)\b|वृद्धावस्था पेंशन|बुज़ुर्ग सहायता|वरिष्ठ नागरिक/i,reply:['Old-age pension eligibility and amounts depend on the scheme and state. Start with the National Social Assistance Programme and your state social-welfare office. Tell me your state and age range to narrow down where to ask.','वृद्धावस्था पेंशन की पात्रता और राशि योजना व राज्य पर निर्भर करती है। National Social Assistance Programme और राज्य के समाज कल्याण कार्यालय से शुरुआत करें। सही कार्यालय जानने के लिए राज्य और आयु वर्ग बताएं।'],steps:[['Tell me your state and age range (do not share your full birth date).','अपना राज्य और आयु वर्ग बताएं (पूरी जन्मतिथि न लिखें)।'],['Ask your Gram Panchayat, municipality, or social-welfare office.','ग्राम पंचायत, नगर निकाय या समाज कल्याण कार्यालय से पूछें।'],['Compare central and state schemes on myScheme.','myScheme पर केंद्र और राज्य की योजनाएं देखें।']],url:'https://nsap.nic.in/',source:'National Social Assistance Programme — Government of India',extra:['myScheme — Government of India','https://www.myscheme.gov.in/']},
  {id:'disability',en:'Disability certificate & support',hi:'दिव्यांगता प्रमाणपत्र और सहायता',prompt:'disability certificate support accommodations',match:/\b(disabilit|udid|accessible|accommodation for disabled|disability support)\w*\b|दिव्यांग|विकलांग|यूडीआईडी|दिव्यांगता प्रमाणपत्र/i,reply:['The UDID portal supports applications for a disability certificate and Unique Disability ID. If online steps are difficult, the Department says applicants can seek help at a designated hospital. State benefits and accommodations may vary.','UDID पोर्टल पर दिव्यांगता प्रमाणपत्र और विशिष्ट दिव्यांग पहचान पत्र के लिए आवेदन किया जा सकता है। ऑनलाइन प्रक्रिया कठिन हो तो निर्धारित अस्पताल से मदद लें। राज्य की सुविधाएं अलग हो सकती हैं।'],steps:[['Ask your district hospital or designated hospital for UDID application help.','UDID आवेदन की मदद के लिए ज़िला या निर्धारित अस्पताल से पूछें।'],['Check the official UDID portal for application and accessibility details.','आवेदन और सुविधा की जानकारी आधिकारिक UDID पोर्टल पर देखें।'],['Tell me your state if you need state-specific pension or support.','राज्य की पेंशन या सहायता जानने के लिए अपना राज्य बताएं।']],url:'https://www.swavlambancard.gov.in/',source:'UDID — Department of Empowerment of Persons with Disabilities'},
  {id:'tax',en:'Income tax & tax filing',hi:'आयकर और टैक्स रिटर्न',prompt:'income tax return filing help',match:/\b(income tax|tax(?:ation)?|revenue filing|file taxes|tax filing|itr|gst return)\b|आयकर|टैक्स रिटर्न|कर भरना|आईटीआर/i,reply:['The Income Tax Department’s e-Filing portal is the official place to learn about and file income-tax returns. Which form applies depends on your situation. Use the portal’s help guides or contact its official helpline; never share your password or OTP here.','आयकर रिटर्न की जानकारी और फाइलिंग के लिए आयकर विभाग का e-Filing पोर्टल सरकारी जगह है। कौन-सा फॉर्म लागू होगा यह आपकी स्थिति पर निर्भर है। पोर्टल की सहायता देखें; पासवर्ड या OTP यहाँ न लिखें।'],steps:[['Open the official Income Tax e-Filing portal.','आयकर विभाग का सरकारी e-Filing पोर्टल खोलें।'],['Use its help guides to identify the correct form for your situation.','अपनी स्थिति के लिए सही फॉर्म पोर्टल की सहायता से समझें।'],['Do not share account passwords, OTPs, or bank details in chat.','चैट में पासवर्ड, OTP या बैंक विवरण साझा न करें।']],url:'https://www.incometax.gov.in/iec/foportal/',source:'Income Tax Department — Government of India'},
];
function offlineGuide(message){
  const text=message.toLowerCase();
  const hi=current==='hi', ta=current==='ta', selectedState=stateSelector.value.replace(' — தமிழ்நாடு','');
  const scheme=(name,benefit,fit,eligibility,steps,url)=>({name,benefit,fit_reason:fit,eligibility_to_check:eligibility,how_to_start:steps,official_url:url});
  const base={intent_summary:hi?'आपकी ज़रूरत के लिए जानकारी':'Guidance for your request',reply:'',follow_up_question:'',schemes:[],next_steps:[],safety_note:hi?'यह शुरुआती जानकारी है। नियम बदल सकते हैं और राज्य के अनुसार अलग हो सकते हैं। किसी को OTP या PIN न बताएं।':'This is a starting guide. Rules can change and may vary by state. Never share an OTP or PIN.',sources:[]};
  const addSource=(title,url)=>base.sources.push({title,url});
  const route=offlineDirectory.find(topic=>topic.match.test(text));
  if(route){
    base.intent_summary=hi?route.hi:route.en;base.reply=hi?route.reply[1]:route.reply[0];base.next_steps=hi?route.steps[1]:route.steps[0];
    base.schemes.push(scheme(route.en,hi?route.reply[1]:route.reply[0],hi?'आपकी ज़रूरत के अनुसार सरकारी सेवा की शुरुआत।':'A starting point for the government service you asked about.',hi?'दस्तावेज़, पात्रता और प्रक्रिया राज्य/स्थानीय कार्यालय से जांचें।':'Check documents, eligibility, and process with the local/state office.',hi?route.steps[1][0]:route.steps[0][0],route.url));
    addSource(route.source,route.url);if(route.extra)addSource(route.extra[0],route.extra[1]);
  }else if(/pension|widow|old.?age|vridh|विधवा|पेंशन|बुढ़ापा|वृद्धावस्था/.test(text)){
    base.intent_summary=hi?'पेंशन की जानकारी':'Pension support';
    base.reply=hi?('आपने '+selectedState+' चुना है। वृद्धावस्था, विधवा और दिव्यांग पेंशन के नियम अपने ज़िला समाज कल्याण कार्यालय से जाँचें। केंद्र और राज्य की योजनाएँ myScheme पर देखें।'):ta?('நீங்கள் '+selectedState+'-ஐத் தேர்ந்தெடுத்துள்ளீர்கள். முதியோர், விதவை மற்றும் மாற்றுத்திறனாளி ஓய்வூதிய விதிகளை உங்கள் மாவட்ட சமூக நல அலுவலகத்தில் சரிபார்க்கவும். myScheme-ல் மத்திய மற்றும் மாநிலத் திட்டங்களைப் பார்க்கவும்.'):('You selected '+selectedState+'. Check old-age, widow, and disability pension rules with your district Social Welfare office. Browse central and state schemes on myScheme.');
    base.follow_up_question='';
    base.next_steps=hi?[selectedState+' के ज़िला समाज कल्याण कार्यालय से पेंशन के बारे में पूछें।','myScheme पर केंद्र और राज्य की योजनाएँ देखें।','पात्रता और दस्तावेज़ की पुष्टि आधिकारिक कार्यालय से करें।']:ta?[selectedState+' மாவட்ட சமூக நல அலுவலகத்தில் ஓய்வூதிய உதவி கேளுங்கள்.','myScheme-ல் மத்திய மற்றும் மாநிலத் திட்டங்களைப் பாருங்கள்.','தகுதி மற்றும் ஆவணங்களை அதிகாரப்பூர்வ அலுவலகத்தில் உறுதிப்படுத்துங்கள்.']:[`Ask your ${selectedState} district Social Welfare office about pension support.`,'Browse central and state schemes on myScheme.','Confirm eligibility and documents with an official office.'];
    addSource('myScheme — Government of India','https://www.myscheme.gov.in/search');
    addSource('National Social Assistance Programme — Government of India','https://nsap.nic.in/');
  }else if(/pregnan|matern|mother|delivery|गर्भवती|गर्भ|मातृत्व|प्रसव/.test(text)){
    base.intent_summary=hi?'गर्भावस्था सहायता':'Maternity support';
    base.reply=hi?'प्रधानमंत्री मातृ वंदना योजना (PMMVY) पात्र महिलाओं के लिए मातृत्व सहायता देती है। पहली संतान के लिए ₹5,000 और दूसरी संतान लड़की होने पर ₹6,000 का प्रावधान है। पात्रता और आवेदन की पुष्टि आंगनवाड़ी/आशा कार्यकर्ता या आधिकारिक पोर्टल से करें।':'Pradhan Mantri Matru Vandana Yojana (PMMVY) offers maternity support to eligible women: ₹5,000 for the first child and ₹6,000 for a second child if the child is a girl. Check eligibility and application steps with an Anganwadi/ASHA worker or the official portal.';
    base.next_steps=hi?['नज़दीकी आंगनवाड़ी या आशा कार्यकर्ता से बात करें।','आधिकारिक PMMVY पोर्टल पर आवेदन की जानकारी देखें।','किसी से OTP या बैंक PIN साझा न करें।']:['Speak with your nearest Anganwadi or ASHA worker.','Check application details on the official PMMVY portal.','Never share an OTP or bank PIN.'];
    base.schemes.push(scheme('Pradhan Mantri Matru Vandana Yojana (PMMVY)','₹5,000 for the first child; ₹6,000 for a second child if the child is a girl.','Maternity support for eligible pregnant and lactating women.','Eligibility categories and conditions apply; confirm them with an Anganwadi/ASHA worker or the official portal.','Visit the official PMMVY portal or ask an Anganwadi/ASHA worker to help.','https://pmmvy.wcd.gov.in/'));
    addSource('Ministry of Women and Child Development','https://wcd.gov.in/women/pradhan-mantri-matru-vandana-yojna');
  }else if(/ujjwala|lpg|gas cylinder|cooking gas|उज्ज्वला|गैस|सिलेंडर/.test(text)){
    base.intent_summary=hi?'गैस कनेक्शन सहायता':'LPG connection support';
    base.reply=hi?'प्रधानमंत्री उज्ज्वला योजना के तहत पात्र गरीब परिवारों की वयस्क महिलाएँ नया LPG कनेक्शन लेने के लिए आवेदन कर सकती हैं। परिवार में पहले से LPG कनेक्शन नहीं होना चाहिए। नज़दीकी गैस वितरक से मदद लें या आधिकारिक वेबसाइट देखें।':'Under Pradhan Mantri Ujjwala Yojana, an adult woman in an eligible poor household may apply for a new LPG connection if the household has no existing LPG connection. Ask a nearby LPG distributor or use the official website.';
    base.next_steps=hi?['नज़दीकी LPG वितरक से आवेदन में मदद माँगें।','ज़रूरी दस्तावेज़ आधिकारिक PMUY वेबसाइट पर देखें।','अपना OTP या बैंक PIN किसी को न बताएं।']:['Ask a nearby LPG distributor for application help.','Check the required documents on the official PMUY website.','Never share your OTP or bank PIN.'];
    base.schemes.push(scheme('Pradhan Mantri Ujjwala Yojana (PMUY)','A new LPG connection for eligible women in poor households.','For an adult woman in a household without an existing LPG connection.','Age, household eligibility, and documents must be confirmed on the official PMUY site or with a distributor.','Apply online or visit an LPG distributor of your choice.','https://www.pmuy.gov.in/ujjwala2.html'));
    addSource('Pradhan Mantri Ujjwala Yojana — Government of India','https://www.pmuy.gov.in/');
  }else{
    base.intent_summary=hi?'सरकारी मदद की खोज':'Finding government help';
    base.reply=hi?'मैं बिना इंटरनेट कनेक्शन के कुछ सामान्य सरकारी योजनाओं की जानकारी दे सकती हूँ। पेंशन, गर्भावस्था सहायता या उज्ज्वला योजना के बारे में पूछें। किसी दूसरी योजना के लिए myScheme पर खोजें।':'I can give offline guidance for a few common government schemes: ask about pension, maternity support, or Ujjwala LPG connections. For other needs, search the Government of India’s myScheme directory.';
    base.next_steps=hi?['अपनी ज़रूरत और राज्य का नाम लिखें।','myScheme की सरकारी योजना सूची देखें।']:['Tell me what help you need and your state.','Browse the official myScheme directory.'];
    addSource('myScheme — Government of India','https://www.myscheme.gov.in/');
  }
  return base;
}
function isOfflineTopic(message){
  return offlineDirectory.some(topic=>topic.match.test(message))||/pension|widow|old.?age|retirement|senior citizen|vridh|विधवा|पेंशन|बुढ़ापा|वृद्धावस्था|गर्भवती|गर्भ|मातृत्व|प्रसव|ujjwala|lpg|gas cylinder|cooking gas|उज्ज्वला|गैस|सिलेंडर/i.test(message);
}
async function askDisha(text){
  if(busy)return;const message=text.trim();if(!message){notify(t('placeholderResponse'));q.focus();return}
  busy=true;document.querySelector('#send-button').disabled=true;q.disabled=true;
  answer.hidden=false;clearGuide();document.querySelector('#ai-loading').hidden=false;document.querySelector('#answer-title').textContent='';answer.scrollIntoView({behavior:'smooth',block:'nearest'});
  try{
    if(location.protocol==='file:'||isOfflineTopic(message)){renderGuide(offlineGuide(message));document.querySelector('#search-hint').textContent=t('offlineHint');document.querySelector('#status-dot').classList.remove('needs-setup');q.value='';return}
    const healthResponse=await fetch('/api/health',{cache:'no-store'});if(!healthResponse.ok){renderGuide(offlineGuide(message));q.value='';return}const health=await healthResponse.json();if(!health.ready){renderGuide(offlineGuide(message));q.value='';return}
    const response=await fetch('/api/guide',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message,language:current,state:stateSelector.value.replace(' — தமிழ்நாடு',''),history:chatHistory.slice(-6)})});
    const data=await response.json();if(!response.ok){renderGuide(offlineGuide(message));document.querySelector('#answer-note').textContent=(data.error||'The live AI answer could not be reached.')+' Showing the built-in guide instead. Check the PowerShell window for the connection detail.';document.querySelector('#search-hint').textContent=t('offlineHint');document.querySelector('#status-dot').classList.remove('needs-setup');q.value='';return}
    renderGuide(data.guide);chatHistory.push({role:'user',content:message},{role:'assistant',content:JSON.stringify(data.guide)});chatHistory=chatHistory.slice(-6);q.value='';
  }catch(error){if(error.name==='TypeError'){renderGuide(offlineGuide(message));document.querySelector('#answer-note').textContent='The live AI service could not be reached. Showing the built-in guide instead.';document.querySelector('#search-hint').textContent=t('offlineHint');document.querySelector('#status-dot').classList.remove('needs-setup');q.value=''}else{document.querySelector('#answer-title').textContent='';document.querySelector('#answer-summary').textContent=error.message||'Disha could not connect. Please try again.';document.querySelector('#official-link').hidden=true}}
  finally{document.querySelector('#ai-loading').hidden=true;busy=false;q.disabled=false;document.querySelector('#send-button').disabled=false}
}
document.querySelector('#ask-form').addEventListener('submit',e=>{e.preventDefault();askDisha(q.value)});
document.querySelectorAll('.topic').forEach(button=>button.addEventListener('click',()=>askDisha(({pension:'pension',health:'public health insurance Ayushman Bharat',documents:'birth registration certificate',work:'job placement or vocational training'})[button.dataset.topic])));
const directoryTopics=[
  {id:'pension',en:'Pension & elderly support',hi:'पेंशन और बुज़ुर्ग सहायता',prompt:'pension'},
  {id:'lpg',en:'LPG connection',hi:'LPG गैस कनेक्शन',prompt:'LPG Ujjwala gas connection'},
  {id:'maternity',en:'Maternity support',hi:'मातृत्व सहायता',prompt:'maternity support'},
  ...offlineDirectory,
];
const directoryGrid=document.querySelector('#directory-grid');
for(const topic of directoryTopics){const button=document.createElement('button');button.type='button';button.className='directory-topic';button.textContent=current==='hi'?topic.hi:topic.en;button.addEventListener('click',()=>{answer.hidden=false;clearGuide();renderGuide(offlineGuide(topic.prompt));answer.scrollIntoView({behavior:'smooth',block:'nearest'})});directoryGrid.append(button)}
document.querySelector('#close-answer').addEventListener('click',()=>answer.hidden=true);
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
let activeRecognition=null;
const voiceStateCopy={
  hi:{downloading:'इस भाषा का आवाज़ पैक डाउनलोड हो रहा है… पूरा होने पर माइक फिर दबाएँ।',installed:'भाषा पैक तैयार है। बोलने के लिए माइक फिर दबाएँ।',downloadFailed:'भाषा पैक डाउनलोड नहीं हुआ। इंटरनेट जाँचें और फिर कोशिश करें।'},
  en:{downloading:'Downloading this language’s speech pack… Tap the mic again when it finishes.',installed:'Speech pack is ready. Tap the mic again to speak.',downloadFailed:'The speech pack could not download. Check your internet and try again.'}
};
const voiceErrors={
  hi:{'not-allowed':'माइक की अनुमति नहीं मिली। ब्राउज़र की साइट सेटिंग में माइक्रोफ़ोन चालू करें।','service-not-allowed':'यहाँ आवाज़ की सुविधा उपलब्ध नहीं है। मोबाइल कीबोर्ड पर माइक दबाकर बोलें।',network:'ब्राउज़र की आवाज़ सेवा तक पहुँचा नहीं जा सका। इंटरनेट जाँचें। कंप्यूटर पर लिखने वाले खाने को चुनकर Windows + H दबाएँ, या मोबाइल कीबोर्ड का माइक इस्तेमाल करें।','language-not-supported':'इस भाषा में इस ब्राउज़र पर आवाज़ की सुविधा उपलब्ध नहीं है। लिखने वाले खाने को चुनकर Windows + H दबाएँ, या लिखें।','audio-capture':'माइक्रोफ़ोन नहीं मिला। अनुमति जाँचें या मोबाइल कीबोर्ड का माइक इस्तेमाल करें।','no-speech':'आवाज़ सुनाई नहीं दी। फिर कोशिश करें या मोबाइल कीबोर्ड का माइक दबाएँ।'},
  en:{'not-allowed':'Microphone access is blocked. Allow it in your browser’s site settings, then try again.','service-not-allowed':'Voice input is unavailable here. Try the microphone on your phone keyboard instead.','network':'The browser could not reach its speech service. Check your internet. Click the text box first, then press Windows + H to dictate, or use your phone keyboard microphone.','language-not-supported':'This browser cannot transcribe the selected language. Click the text box first, then press Windows + H to dictate, or type instead.','audio-capture':'No microphone was found. Check access or use the keyboard microphone.','no-speech':'No speech was heard. Try again or use the microphone on your phone keyboard.'},
  bn:{'not-allowed':'মাইক্রোফোনের অনুমতি নেই। ব্রাউজারের সাইট সেটিংসে অনুমতি দিন।','service-not-allowed':'এখানে ভয়েস কাজ করছে না। ফোনের কিবোর্ডের মাইক ব্যবহার করে দেখুন।','network':'স্পিচ পরিষেবায় পৌঁছানো যায়নি। ইন্টারনেট দেখুন বা কিবোর্ডের মাইক ব্যবহার করুন।','audio-capture':'মাইক্রোফোন পাওয়া যায়নি। অনুমতি দেখুন বা কিবোর্ডের মাইক ব্যবহার করুন।','no-speech':'কথা শোনা যায়নি। আবার বলুন বা কিবোর্ডের মাইক ব্যবহার করুন।'},
  ta:{'not-allowed':'மைக்ரோஃபோன் அனுமதி இல்லை. உலாவி அமைப்புகளில் அனுமதிக்கவும்.','service-not-allowed':'இங்கே குரல் உள்ளீடு கிடைக்கவில்லை. கைபேசி விசைப்பலகை மைக்கைப் பயன்படுத்தவும்.','network':'குரல் சேவையை அணுக முடியவில்லை. இணையத்தைச் சரிபார்க்கவும் அல்லது விசைப்பலகை மைக்கைப் பயன்படுத்தவும்.','audio-capture':'மைக்ரோஃபோன் கிடைக்கவில்லை. அனுமதியைச் சரிபார்க்கவும் அல்லது விசைப்பலகை மைக்கைப் பயன்படுத்தவும்.','no-speech':'குரல் கேட்கவில்லை. மீண்டும் முயற்சிக்கவும் அல்லது விசைப்பலகை மைக்கைப் பயன்படுத்தவும்.'},
  te:{'not-allowed':'మైక్రోఫోన్ అనుమతి లేదు. బ్రౌజర్ సైట్ సెట్టింగ్స్‌లో అనుమతించండి.','service-not-allowed':'ఇక్కడ వాయిస్ అందుబాటులో లేదు. ఫోన్ కీబోర్డ్ మైక్‌ను ప్రయత్నించండి.','network':'వాయిస్ సేవను చేరుకోలేకపోయాం. ఇంటర్నెట్ తనిఖీ చేయండి లేదా కీబోర్డ్ మైక్ వాడండి.','audio-capture':'మైక్రోఫోన్ దొరకలేదు. అనుమతి తనిఖీ చేయండి లేదా కీబోర్డ్ మైక్ వాడండి.','no-speech':'మాట వినిపించలేదు. మళ్లీ ప్రయత్నించండి లేదా కీబోర్డ్ మైక్ వాడండి.'},
  mr:{'not-allowed':'मायक्रोफोनची परवानगी नाही. ब्राउझरच्या साइट सेटिंग्जमध्ये परवानगी द्या.','service-not-allowed':'इथे आवाजाची सुविधा उपलब्ध नाही. फोनच्या कीबोर्डवरील माइक वापरून पाहा.','network':'आवाज सेवा उपलब्ध झाली नाही. इंटरनेट तपासा किंवा कीबोर्डवरील माइक वापरा.','audio-capture':'मायक्रोफोन सापडला नाही. परवानगी तपासा किंवा कीबोर्डवरील माइक वापरा.','no-speech':'आवाज ऐकू आला नाही. पुन्हा प्रयत्न करा किंवा कीबोर्डवरील माइक वापरा.'}
};
function stopListening(){mic.classList.remove('listening');micTitle.textContent=t('micTitle')}
mic.addEventListener('click',()=>{
  if(!SpeechRecognition){micHint.textContent=t('voiceUnsupported');notify(t('voiceUnsupported'));return}
  if(mic.classList.contains('listening')){try{activeRecognition?.stop()}catch{}stopListening();return}
  const recognition=new SpeechRecognition();
  activeRecognition=recognition;
  recognition.lang={as:'as-IN',bn:'bn-IN',brx:'brx-IN',doi:'doi-IN',en:'en-IN',gu:'gu-IN',hi:'hi-IN',kn:'kn-IN',ks:'ks-IN',kok:'kok-IN',mai:'mai-IN',ml:'ml-IN',mni:'mni-IN',mr:'mr-IN',ne:'ne-IN',or:'or-IN',pa:'pa-IN',sa:'sa-IN',sat:'sat-IN',sd:'sd-IN',ta:'ta-IN',te:'te-IN',ur:'ur-IN'}[current]||'hi-IN';
  recognition.interimResults=false;recognition.maxAlternatives=1;
  recognition.onresult=event=>{const spoken=event.results?.[0]?.[0]?.transcript;if(!spoken){notify(t('noSpeech'));return}q.value=spoken;askDisha(spoken)};
  recognition.onerror=event=>{const message=(voiceErrors[current]||voiceErrors.en)[event.error]||t('noSpeech');micHint.textContent=message;notify(message);if(event.error==='network'||event.error==='language-not-supported')q.focus()};
  recognition.onend=()=>{activeRecognition=null;stopListening();if(q.value)micHint.textContent=t('micHint')};
  const startSafely=()=>{try{recognition.start()}catch(error){activeRecognition=null;stopListening();const key=error.name==='NotAllowedError'?'not-allowed':'no-speech';const message=(voiceErrors[current]||voiceErrors.en)[key]||t('noSpeech');micHint.textContent=message;notify(message)}};
  mic.classList.add('listening');micTitle.textContent=t('listening');micHint.textContent=t('micHint');
  if(typeof SpeechRecognition.available==='function'&&typeof SpeechRecognition.install==='function'&&'processLocally' in recognition){
    SpeechRecognition.available({langs:[recognition.lang],processLocally:true}).then(async status=>{
      if(status==='available'){recognition.processLocally=true;startSafely();return}
      if(status==='downloadable'||status==='downloading'){
        stopListening();micHint.textContent=(voiceStateCopy[current]||voiceStateCopy.en).downloading;
        const installed=await SpeechRecognition.install({langs:[recognition.lang],processLocally:true});
        const message=(voiceStateCopy[current]||voiceStateCopy.en)[installed?'installed':'downloadFailed'];micHint.textContent=message;notify(message);return;
      }
      recognition.processLocally=false;startSafely();
    }).catch(()=>{recognition.processLocally=false;startSafely()});
  }else startSafely();
});
applyLanguage(language.value);

