(function () {
const offlineDirectory = [
  {id:'birth',en:'Birth registration & certificates',hi:'जन्म पंजीकरण और प्रमाणपत्र',prompt:'birth registration certificate',match:/\b(birth|born|birth certificate|birth registration)\b|जन्म|जन्म प्रमाण पत्र|जन्म पंजीकरण/i,reply:['For a birth certificate, contact the local Registrar of Births and Deaths or your municipal office. Online registration is available only in some states and areas, so choose your state on the official Civil Registration System portal.','जन्म प्रमाणपत्र के लिए स्थानीय जन्म-मृत्यु रजिस्ट्रार या नगर निकाय से संपर्क करें। ऑनलाइन सुविधा कुछ राज्यों और क्षेत्रों में ही उपलब्ध है; आधिकारिक नागरिक पंजीकरण पोर्टल पर अपना राज्य चुनें।'],steps:[['Tell me your state or district for the correct office.','अपने राज्य या ज़िले का नाम बताएं ताकि सही कार्यालय खोज सकें।'],['Ask the local registrar or municipal office how to register the birth.','स्थानीय रजिस्ट्रार या नगर कार्यालय से पंजीकरण का तरीका पूछें।'],['Use only the official government portal; requirements and time limits can vary.','केवल सरकारी पोर्टल इस्तेमाल करें; दस्तावेज़ और समय-सीमा अलग हो सकती है।']],url:'https://dc.crsorgi.gov.in/crs/ReportEvent/ReportBirth',source:'Civil Registration System — Government of India'},
  {id:'identity',en:'Identity cards & worker registration',hi:'पहचान पत्र और श्रमिक पंजीकरण',prompt:'Aadhaar identity card or e-Shram registration',match:/\b(aadhaar|identity card|national id|social security|e.?shram|worker registration)\b|आधार|पहचान पत्र|श्रमिक पंजीकरण/i,reply:['India does not use a US-style Social Security Number. For identity services, use UIDAI’s Aadhaar information; unorganised workers can check e-Shram. Do not enter your Aadhaar number, OTP, or PIN here.','भारत में अमेरिका जैसा Social Security Number नहीं है। पहचान संबंधी सेवाओं के लिए UIDAI की आधार जानकारी देखें; असंगठित कामगार e-Shram देख सकते हैं। अपना आधार नंबर, OTP या PIN यहाँ न लिखें।'],steps:[['Choose whether you need Aadhaar help or worker registration.','बताएं कि आपको आधार सहायता चाहिए या श्रमिक पंजीकरण।'],['For Aadhaar, contact an authorized Aadhaar centre listed by UIDAI.','आधार के लिए UIDAI द्वारा सूचीबद्ध अधिकृत केंद्र जाएं।'],['Never share an OTP or full identity number in chat or with an agent.','चैट या एजेंट के साथ OTP या पूरा पहचान नंबर साझा न करें।']],url:'https://uidai.gov.in/',source:'UIDAI — Government of India',extra:['e-Shram — Government of India','https://eshram.gov.in/']},
  {id:'passport',en:'Passport & travel documents',hi:'पासपोर्ट और यात्रा दस्तावेज़',prompt:'apply for a passport',match:/\b(passport|travel document|visa)\b|पासपोर्ट|यात्रा दस्तावेज़/i,reply:['Apply for an Indian passport through Passport Seva, the Ministry of External Affairs portal. The usual process is to register, submit the application, pay the applicable fee, book an appointment, and visit a Passport Seva Kendra. Check the current document list and fee there.','भारतीय पासपोर्ट के लिए विदेश मंत्रालय के Passport Seva पोर्टल का उपयोग करें। आम तौर पर पंजीकरण, आवेदन, लागू शुल्क, अपॉइंटमेंट और पासपोर्ट सेवा केंद्र जाना होता है। मौजूदा दस्तावेज़ और शुल्क वहीं जांचें।'],steps:[['Use the official Passport Seva website only.','केवल आधिकारिक Passport Seva वेबसाइट इस्तेमाल करें।'],['Read the fresh-passport or re-issue guide that matches your need.','अपनी ज़रूरत के अनुसार नया पासपोर्ट या नवीनीकरण गाइड चुनें।'],['Check fees and required documents before paying or booking.','भुगतान या अपॉइंटमेंट से पहले शुल्क और दस्तावेज़ जांचें।']],url:'https://www.passportindia.gov.in/psp/GettingStarted',source:'Passport Seva — Ministry of External Affairs'},
  {id:'death',en:'Death registration & legal next steps',hi:'मृत्यु पंजीकरण और कानूनी अगले कदम',prompt:'death certificate and legal heir help',match:/\b(death certificate|death registration|estate settlement|inheritance|legal heir|succession)\b|मृत्यु प्रमाण पत्र|मृत्यु पंजीकरण|उत्तराधिकार|वारिस/i,reply:['A death must be registered with the local Registrar of Births and Deaths or municipal office. Estate, inheritance, and legal-heir steps depend on the situation and local rules; free legal aid is available through NALSA.','मृत्यु का पंजीकरण स्थानीय जन्म-मृत्यु रजिस्ट्रार या नगर निकाय में कराएं। संपत्ति, उत्तराधिकार और कानूनी वारिस की प्रक्रिया स्थिति व नियमों पर निर्भर करती है; NALSA से निःशुल्क कानूनी सहायता मिल सकती है।'],steps:[['Ask the local registrar how to register the death and request a certificate.','स्थानीय रजिस्ट्रार से मृत्यु पंजीकरण और प्रमाणपत्र की प्रक्रिया पूछें।'],['For property or inheritance questions, contact your District Legal Services Authority.','संपत्ति या उत्तराधिकार के लिए ज़िला विधिक सेवा प्राधिकरण से संपर्क करें।'],['Do not share account numbers, passwords, or OTPs with anyone.','किसी के साथ खाता नंबर, पासवर्ड या OTP साझा न करें।']],url:'https://dc.crsorgi.gov.in/crs/ReportEvent/ReportBirth',source:'Civil Registration System — Government of India',extra:['NALSA — Free legal aid','https://nalsa.gov.in/promoting-inclusive-legal-system/']},
  {id:'insurance',en:'Public health insurance',hi:'सरकारी स्वास्थ्य बीमा',prompt:'government health insurance Ayushman Bharat',match:/\b(health insurance|medical insurance|ayushman|pm.?jay|health cover|hospital cover)\b|स्वास्थ्य बीमा|आयुष्मान|इलाज का खर्च/i,reply:['Ayushman Bharat PM-JAY provides health-cover benefits to eligible families. Check whether your family is eligible through the official beneficiary portal or ask an Ayushman Mitra at a listed hospital. The guide cannot confirm eligibility.','आयुष्मान भारत PM-JAY पात्र परिवारों को स्वास्थ्य कवर देता है। आधिकारिक लाभार्थी पोर्टल पर जांचें या सूचीबद्ध अस्पताल के आयुष्मान मित्र से पूछें। यह गाइड पात्रता की पुष्टि नहीं कर सकती।'],steps:[['Check eligibility on the official beneficiary portal.','आधिकारिक लाभार्थी पोर्टल पर पात्रता जांचें।'],['Ask an Ayushman Mitra at a participating hospital for help.','सूचीबद्ध अस्पताल में आयुष्मान मित्र से सहायता लें।'],['Never pay an agent to “guarantee” eligibility.','पात्रता की “गारंटी” देने वाले एजेंट को पैसे न दें।']],url:'https://beneficiary.nha.gov.in/',source:'National Health Authority — Government of India'},
  {id:'immunization',en:'Vaccination & immunization',hi:'टीकाकरण',prompt:'vaccination immunization for child',match:/\b(vaccin|immuni[sz]|immunization|uwin|vaccine|infectious disease|disease control|communicable disease)\w*\b|टीका|टीकाकरण|प्रतिरक्षण|संक्रामक रोग/i,reply:['Government vaccination for pregnant women and children is delivered through health facilities and tracked on U-WIN. Ask an ASHA worker or health centre about due doses, appointments, and vaccination records.','गर्भवती महिलाओं और बच्चों का सरकारी टीकाकरण स्वास्थ्य केंद्रों पर होता है और U-WIN पर दर्ज किया जाता है। बाकी टीकों, अपॉइंटमेंट और रिकॉर्ड के लिए आशा कार्यकर्ता या स्वास्थ्य केंद्र से पूछें।'],steps:[['Contact your nearest government health centre or ASHA worker.','नज़दीकी सरकारी स्वास्थ्य केंद्र या आशा कार्यकर्ता से संपर्क करें।'],['Use U-WIN to check the available citizen services.','U-WIN पर उपलब्ध नागरिक सेवाएं देखें।'],['For a medical concern or reaction, contact a qualified health professional.','स्वास्थ्य समस्या या प्रतिक्रिया के लिए योग्य स्वास्थ्यकर्मी से संपर्क करें।']],url:'https://uwindashboard.mohfw.gov.in/',source:'U-WIN — Ministry of Health and Family Welfare'},
  {id:'emergency',en:'Emergency medical help',hi:'आपातकालीन चिकित्सा सहायता',prompt:'emergency ambulance medical help',match:/\b(emergency|ambulance|first responder|urgent medical|medical emergency)\b|आपातकाल|एम्बुलेंस|तुरंत चिकित्सा/i,reply:['If someone is in immediate danger or needs urgent medical help, call India’s emergency number 112 now. This is for emergencies.','अगर कोई तत्काल खतरे में है या तुरंत चिकित्सा सहायता चाहिए, अभी भारत के आपातकालीन नंबर 112 पर कॉल करें। यह आपात स्थिति के लिए है।'],steps:[['Call 112 for urgent police, fire, or medical assistance.','तत्काल पुलिस, अग्निशमन या चिकित्सा सहायता के लिए 112 पर कॉल करें।'],['Share your location and the type of emergency with the responder.','सहायता दल को अपना स्थान और आपात स्थिति बताएं।']],url:'https://112.gov.in/',source:'Emergency Response Support System — Government of India'},
  {id:'schools',en:'Government schools & school education',hi:'सरकारी स्कूल और शिक्षा',prompt:'government school admission for my child',match:/\b(school|primary education|secondary education|school admission|government school)\b|स्कूल|विद्यालय|प्राथमिक शिक्षा|माध्यमिक शिक्षा/i,reply:['For a government school, ask the nearest school or your block/district education office about admission, age rules, and required documents. School services and procedures can differ by state.','सरकारी स्कूल में प्रवेश के लिए नज़दीकी स्कूल या ब्लॉक/ज़िला शिक्षा कार्यालय से आयु नियम और दस्तावेज़ पूछें। प्रवेश की प्रक्रिया राज्य के अनुसार बदल सकती है।'],steps:[['Tell me your state and the child’s class to narrow down the right office.','सही कार्यालय बताने के लिए राज्य और कक्षा बताएं।'],['Contact the nearest government school or district education office.','नज़दीकी सरकारी स्कूल या ज़िला शिक्षा कार्यालय से संपर्क करें।'],['Ask about admission dates, age requirements, and local documents.','प्रवेश की तारीख, आयु और स्थानीय दस्तावेज़ पूछें।']],url:'https://samagra.education.gov.in/',source:'Samagra Shiksha — Department of School Education'},
  {id:'highereducation',en:'College scholarships & vocational training',hi:'कॉलेज छात्रवृत्ति और कौशल प्रशिक्षण',prompt:'scholarship or skill training for college',match:/\b(higher education|college scholarship|scholarship|vocational|skill training|iti|training course)\b|छात्रवृत्ति|कॉलेज|उच्च शिक्षा|कौशल प्रशिक्षण|आईटीआई/i,reply:['For scholarships, look at the National Scholarship Portal and check each scheme’s eligibility and dates. For vocational courses and training centres, Skill India Digital Hub lists options. Availability and fees vary by course and state.','छात्रवृत्ति के लिए National Scholarship Portal पर योजनाएं और उनकी पात्रता व तारीखें जांचें। व्यावसायिक कोर्स और प्रशिक्षण केंद्रों के लिए Skill India Digital Hub देखें। कोर्स व राज्य के अनुसार उपलब्धता और शुल्क बदलते हैं।'],steps:[['Search the National Scholarship Portal for the current academic year.','मौजूदा शैक्षणिक वर्ष के लिए National Scholarship Portal पर खोजें।'],['Search Skill India Digital Hub for a course or nearby centre.','कोर्स या नज़दीकी केंद्र के लिए Skill India Digital Hub देखें।'],['Confirm eligibility, fees, and dates with the official provider.','पात्रता, शुल्क और तारीखें आधिकारिक संस्था से पक्का करें।']],url:'https://scholarships.gov.in/',source:'National Scholarship Portal — Government of India',extra:['Skill India Digital Hub','https://www.skillindiadigital.gov.in/']},
  {id:'library',en:'Public libraries & digital literacy',hi:'सरकारी पुस्तकालय और डिजिटल साक्षरता',prompt:'public library or learn digital skills',match:/\b(library|public library|digital literacy|computer class|computer training|learn computer)\b|पुस्तकालय|डिजिटल साक्षरता|कंप्यूटर सीखना/i,reply:['Public libraries and digital-learning centres are usually managed locally. Ask your Gram Panchayat, municipality, or district library about a nearby centre, opening hours, and classes. The Ministry of Culture shares information about public-library initiatives.','सार्वजनिक पुस्तकालय और डिजिटल शिक्षा केंद्र आम तौर पर स्थानीय स्तर पर चलते हैं। नज़दीकी केंद्र, समय और कक्षाओं के लिए ग्राम पंचायत, नगर निकाय या ज़िला पुस्तकालय से पूछें। संस्कृति मंत्रालय सार्वजनिक पुस्तकालयों की जानकारी देता है।'],steps:[['Tell me your village, town, or district to look for local options.','नज़दीकी विकल्प खोजने के लिए गांव, शहर या ज़िला बताएं।'],['Ask your Panchayat or municipal office about the nearest library or digital centre.','नज़दीकी पुस्तकालय या डिजिटल केंद्र के लिए पंचायत या नगर कार्यालय से पूछें।'],['Check opening hours and whether classes are free before visiting.','जाने से पहले समय और कक्षाओं का शुल्क पूछें।']],url:'https://culture.gov.in/national-mission-libraries',source:'National Mission on Libraries — Ministry of Culture',extra:['Common Services Centres','https://csc.gov.in/']},
  {id:'police',en:'Police help & reporting a crime',hi:'पुलिस सहायता और शिकायत',prompt:'contact police or report a crime',match:/\b(police|law enforcement|community policing|report a crime|cyber crime|cyber fraud)\b|पुलिस|अपराध की शिकायत|साइबर अपराध/i,reply:['If there is immediate danger, call 112. For other matters, contact your nearest police station or your state police website. For online financial cyber-fraud, call 1930 quickly and report at the official National Cyber Crime portal.','तत्काल खतरे में 112 पर कॉल करें। अन्य मामलों में नज़दीकी थाने या राज्य पुलिस वेबसाइट से संपर्क करें। ऑनलाइन वित्तीय साइबर धोखाधड़ी के लिए जल्द 1930 पर कॉल करें और सरकारी साइबर अपराध पोर्टल पर शिकायत करें।'],steps:[['For an emergency, call 112.','आपात स्थिति में 112 पर कॉल करें।'],['For online financial fraud, call 1930 and use the National Cyber Crime portal.','ऑनलाइन वित्तीय धोखाधड़ी में 1930 पर कॉल करें और सरकारी साइबर अपराध पोर्टल इस्तेमाल करें।'],['Never share an OTP, PIN, or password with a caller.','कॉल करने वाले को OTP, PIN या पासवर्ड न बताएं।']],url:'https://112.gov.in/',source:'Emergency Response Support System — Government of India',extra:['National Cyber Crime Reporting Portal','https://cybercrime.gov.in/']},
  {id:'fire',en:'Fire & rescue services',hi:'अग्निशमन और बचाव सेवा',prompt:'fire or rescue emergency',match:/\b(fire|fire brigade|rescue service|fire rescue)\b|आग|दमकल|अग्निशमन|बचाव सेवा/i,reply:['If there is a fire or someone needs urgent rescue, move to a safe place and call 112. India’s emergency response system connects requests for police, fire, and medical help.','आग लगने या तुरंत बचाव की ज़रूरत पर सुरक्षित जगह जाएं और 112 पर कॉल करें। भारत की आपातकालीन सेवा पुलिस, अग्निशमन और चिकित्सा सहायता से जोड़ती है।'],steps:[['Move away from smoke and danger if it is safe to do so.','अगर सुरक्षित हो तो धुएं और खतरे से दूर जाएं।'],['Call 112 and describe the location and emergency.','112 पर कॉल करके स्थान और आपात स्थिति बताएं।']],url:'https://112.gov.in/',source:'Emergency Response Support System — Government of India'},
  {id:'legal',en:'Courts & free legal aid',hi:'अदालत और निःशुल्क कानूनी सहायता',prompt:'free legal aid or court help',match:/\b(legal aid|free lawyer|court|judicial|judge|lawyer|estate|inheritance|succession)\b|कानूनी सहायता|मुफ्त वकील|अदालत|न्यायालय|उत्तराधिकार/i,reply:['Women can seek free legal aid through NALSA or their District Legal Services Authority. Call the NALSA toll-free helpline 15100 or visit the district court legal-services office. For case status, use the official eCourts service.','महिलाएं NALSA या ज़िला विधिक सेवा प्राधिकरण से निःशुल्क कानूनी सहायता मांग सकती हैं। NALSA के टोल-फ्री नंबर 15100 पर कॉल करें या ज़िला अदालत के विधिक सेवा कार्यालय जाएं। केस की स्थिति के लिए सरकारी eCourts सेवा देखें।'],steps:[['Call NALSA at 15100 or visit your District Legal Services Authority.','NALSA 15100 पर कॉल करें या ज़िला विधिक सेवा प्राधिकरण जाएं।'],['For a case-status search, use the official eCourts portal.','केस की स्थिति के लिए सरकारी eCourts पोर्टल इस्तेमाल करें।'],['Do not post private case papers or personal details in this chat.','निजी केस कागज़ या व्यक्तिगत जानकारी यहाँ न भेजें।']],url:'https://nalsa.gov.in/promoting-inclusive-legal-system/',source:'NALSA — Government of India',extra:['eCourts Services','https://ecourts.gov.in/']},
  {id:'water',en:'Water supply & sanitation',hi:'पानी की सुविधा और स्वच्छता',prompt:'tap water toilet sanitation help',match:/\b(clean water|tap water|water supply|drinking water|sanitation|toilet|sewer)\b|पीने का पानी|नल का पानी|पानी की आपूर्ति|स्वच्छता|शौचालय/i,reply:['For a broken tap-water supply or sanitation issue, contact your Gram Panchayat or urban local body first. Jal Jeevan Mission and Swachh Bharat Mission explain the national programmes; local delivery and complaints are handled by state and local offices.','नल के पानी या स्वच्छता की समस्या के लिए पहले ग्राम पंचायत या नगर निकाय से संपर्क करें। जल जीवन मिशन और स्वच्छ भारत मिशन राष्ट्रीय कार्यक्रमों की जानकारी देते हैं; स्थानीय सेवा व शिकायत राज्य/स्थानीय कार्यालय देखते हैं।'],steps:[['Tell me your state and village/town.','अपना राज्य और गांव/शहर बताएं।'],['Report a broken connection or sanitation issue to your Panchayat or municipal office.','खराब कनेक्शन या स्वच्छता समस्या पंचायत या नगर कार्यालय में बताएं।'],['Use the official mission pages to learn about the programme.','कार्यक्रम की जानकारी के लिए सरकारी मिशन पेज देखें।']],url:'https://jaljeevanmission.gov.in/',source:'Jal Jeevan Mission — Government of India',extra:['Swachh Bharat Mission (Gramin)','https://swachhbharatmission.ddws.gov.in/']},
  {id:'transport',en:'Public transport & trains',hi:'सरकारी बस और रेल सेवा',prompt:'public transport bus or train',match:/\b(public transport|public transportation|bus route|government bus|train ticket|railway|subway|metro)\b|बस सेवा|रेल|ट्रेन|मेट्रो|सार्वजनिक परिवहन/i,reply:['Bus and metro services are run by state or city transport agencies, so routes and fares depend on where you live. For Indian Railways information, use the official railways portal. Tell me your city or state for more specific guidance.','बस और मेट्रो सेवाएं राज्य या शहर की परिवहन संस्था चलाती है; मार्ग और किराया स्थान के अनुसार बदलते हैं। भारतीय रेल की जानकारी के लिए रेलवे का सरकारी पोर्टल देखें। बेहतर मार्गदर्शन के लिए शहर या राज्य बताएं।'],steps:[['Tell me your city and where you need to go.','अपना शहर और गंतव्य बताएं।'],['For bus/metro routes, check the state or city transport department.','बस/मेट्रो के लिए राज्य या शहर के परिवहन विभाग से पूछें।'],['For trains, use the official Indian Railways information portal.','ट्रेन के लिए भारतीय रेल का आधिकारिक सूचना पोर्टल इस्तेमाल करें।']],url:'https://indianrail.gov.in/',source:'Indian Railways — Government of India'},
  {id:'waste',en:'Garbage collection & recycling',hi:'कचरा उठाना और पुनर्चक्रण',prompt:'garbage collection waste recycling',match:/\b(waste|garbage|rubbish|trash|recycl|waste management|garbage collection)\b|कचरा|कूड़ा|रीसायकल|पुनर्चक्रण/i,reply:['Household waste pickup, recycling, and public-bin complaints are managed by your Gram Panchayat or municipal body. Ask about collection days, sorting rules, and the local complaint desk; these differ by area.','घर का कचरा उठाना, पुनर्चक्रण और सार्वजनिक डिब्बों की शिकायत ग्राम पंचायत या नगर निकाय देखता है। कचरा लेने के दिन, अलग करने के नियम और शिकायत कार्यालय अपने क्षेत्र में पूछें।'],steps:[['Tell me your village, town, or city.','अपना गांव, कस्बा या शहर बताएं।'],['Ask the local body about pickup days and waste sorting.','कचरा उठाने के दिन और अलग करने के तरीके स्थानीय निकाय से पूछें।'],['Report missed collection to the municipal or Panchayat complaint desk.','कचरा न उठने पर नगर या पंचायत शिकायत कार्यालय में बताएं।']],url:'https://swachhbharatmission.ddws.gov.in/',source:'Swachh Bharat Mission — Government of India'},
  {id:'jobs',en:'Jobs & employment services',hi:'नौकरी और रोज़गार सेवा',prompt:'find a job or employment support',match:/\b(unemployment|unemployed|job placement|find a job|job search|employment service|career centre)\b|बेरोज़गार|नौकरी ढूंढ|रोज़गार|काम ढूंढ/i,reply:['The National Career Service (NCS) is a Government of India job and career portal. It lists jobs, career centres, and other services. NCS says its services are free; do not pay anyone claiming to guarantee a job.','National Career Service (NCS) भारत सरकार का नौकरी और करियर पोर्टल है। यहाँ नौकरी, करियर केंद्र और दूसरी सेवाएं मिलती हैं। NCS की सेवाएं निःशुल्क हैं; नौकरी की गारंटी के नाम पर किसी को पैसे न दें।'],steps:[['Open NCS and choose jobseeker services or search jobs.','NCS खोलें और नौकरी खोजने की सेवा चुनें।'],['Tell me your city and the kind of work you want for more guidance.','और मदद के लिए अपना शहर और काम का प्रकार बताएं।'],['NCS services are free; avoid agents charging placement fees.','NCS सेवाएं मुफ्त हैं; नौकरी दिलाने के नाम पर फीस मांगने वालों से बचें।']],url:'https://www.ncs.gov.in/',source:'National Career Service — Ministry of Labour & Employment'},
  {id:'retirement',en:'Old-age pension & elderly support',hi:'वृद्धावस्था पेंशन और बुज़ुर्ग सहायता',prompt:'old age pension elderly support',match:/\b(retirement pension|old.?age pension|elderly care|senior citizen support|senior citizen pension)\b|वृद्धावस्था पेंशन|बुज़ुर्ग सहायता|वरिष्ठ नागरिक/i,reply:['Old-age pension eligibility and amounts depend on the scheme and state. Start with the National Social Assistance Programme and your state social-welfare office. Tell me your state and age range to narrow down where to ask.','वृद्धावस्था पेंशन की पात्रता और राशि योजना व राज्य पर निर्भर करती है। National Social Assistance Programme और राज्य के समाज कल्याण कार्यालय से शुरुआत करें। सही कार्यालय जानने के लिए राज्य और आयु वर्ग बताएं।'],steps:[['Tell me your state and age range (do not share your full birth date).','अपना राज्य और आयु वर्ग बताएं (पूरी जन्मतिथि न लिखें)।'],['Ask your Gram Panchayat, municipality, or social-welfare office.','ग्राम पंचायत, नगर निकाय या समाज कल्याण कार्यालय से पूछें।'],['Compare central and state schemes on myScheme.','myScheme पर केंद्र और राज्य की योजनाएं देखें।']],url:'https://nsap.nic.in/',source:'National Social Assistance Programme — Government of India',extra:['myScheme — Government of India','https://www.myscheme.gov.in/']},
  {id:'disability',en:'Disability certificate & support',hi:'दिव्यांगता प्रमाणपत्र और सहायता',prompt:'disability certificate support accommodations',match:/\b(disabilit|udid|accessible|accommodation for disabled|disability support)\w*\b|दिव्यांग|विकलांग|यूडीआईडी|दिव्यांगता प्रमाणपत्र/i,reply:['The UDID portal supports applications for a disability certificate and Unique Disability ID. If online steps are difficult, the Department says applicants can seek help at a designated hospital. State benefits and accommodations may vary.','UDID पोर्टल पर दिव्यांगता प्रमाणपत्र और विशिष्ट दिव्यांग पहचान पत्र के लिए आवेदन किया जा सकता है। ऑनलाइन प्रक्रिया कठिन हो तो निर्धारित अस्पताल से मदद लें। राज्य की सुविधाएं अलग हो सकती हैं।'],steps:[['Ask your district hospital or designated hospital for UDID application help.','UDID आवेदन की मदद के लिए ज़िला या निर्धारित अस्पताल से पूछें।'],['Check the official UDID portal for application and accessibility details.','आवेदन और सुविधा की जानकारी आधिकारिक UDID पोर्टल पर देखें।'],['Tell me your state if you need state-specific pension or support.','राज्य की पेंशन या सहायता जानने के लिए अपना राज्य बताएं।']],url:'https://www.swavlambancard.gov.in/',source:'UDID — Department of Empowerment of Persons with Disabilities'},
  {id:'tax',en:'Income tax & tax filing',hi:'आयकर और टैक्स रिटर्न',prompt:'income tax return filing help',match:/\b(income tax|tax(?:ation)?|revenue filing|file taxes|tax filing|itr|gst return)\b|आयकर|टैक्स रिटर्न|कर भरना|आईटीआर/i,reply:['The Income Tax Department’s e-Filing portal is the official place to learn about and file income-tax returns. Which form applies depends on your situation. Use the portal’s help guides or contact its official helpline; never share your password or OTP here.','आयकर रिटर्न की जानकारी और फाइलिंग के लिए आयकर विभाग का e-Filing पोर्टल सरकारी जगह है। कौन-सा फॉर्म लागू होगा यह आपकी स्थिति पर निर्भर है। पोर्टल की सहायता देखें; पासवर्ड या OTP यहाँ न लिखें।'],steps:[['Open the official Income Tax e-Filing portal.','आयकर विभाग का सरकारी e-Filing पोर्टल खोलें।'],['Use its help guides to identify the correct form for your situation.','अपनी स्थिति के लिए सही फॉर्म पोर्टल की सहायता से समझें।'],['Do not share account passwords, OTPs, or bank details in chat.','चैट में पासवर्ड, OTP या बैंक विवरण साझा न करें।']],url:'https://www.incometax.gov.in/iec/foportal/',source:'Income Tax Department — Government of India'},
];
function createOfflineGuide(message, { language = 'en', state = 'Tamil Nadu' } = {}) {
  const text = message.toLowerCase();
  const isHindi = language === 'hi';
  const isTamil = language === 'ta';
  const selectedState = state.replace(' — தமிழ்நாடு', '');
  const makeScheme = (name, benefit, fit, eligibility, steps, url) => ({
    name,
    benefit,
    fit_reason: fit,
    eligibility_to_check: eligibility,
    how_to_start: steps,
    official_url: url,
  });
  const guide = {
    intent_summary: isHindi ? 'आपकी ज़रूरत के लिए जानकारी' : 'Guidance for your request',
    reply: '',
    follow_up_question: '',
    schemes: [],
    next_steps: [],
    safety_note: isHindi
      ? 'यह शुरुआती जानकारी है। नियम बदल सकते हैं और राज्य के अनुसार अलग हो सकते हैं। किसी को OTP या PIN न बताएं।'
      : 'This is a starting guide. Rules can change and may vary by state. Never share an OTP or PIN.',
    sources: [],
  };
  const addSource = (title, url) => guide.sources.push({ title, url });
  const matchedTopic = offlineDirectory.find((topic) => topic.match.test(text));

  if (matchedTopic) {
    guide.intent_summary = isHindi ? matchedTopic.hi : matchedTopic.en;
    guide.reply = isHindi ? matchedTopic.reply[1] : matchedTopic.reply[0];
    guide.next_steps = isHindi ? matchedTopic.steps[1] : matchedTopic.steps[0];
    guide.schemes.push(makeScheme(
      matchedTopic.en,
      guide.reply,
      isHindi
        ? 'आपकी ज़रूरत के अनुसार सरकारी सेवा की शुरुआत।'
        : 'A starting point for the government service you asked about.',
      isHindi
        ? 'दस्तावेज़, पात्रता और प्रक्रिया राज्य/स्थानीय कार्यालय से जांचें।'
        : 'Check documents, eligibility, and process with the local/state office.',
      guide.next_steps[0],
      matchedTopic.url,
    ));
    addSource(matchedTopic.source, matchedTopic.url);
    if (matchedTopic.extra) addSource(matchedTopic.extra[0], matchedTopic.extra[1]);
  } else if (/pension|widow|old.?age|vridh|विधवा|पेंशन|बुढ़ापा|वृद्धावस्था/.test(text)) {
    guide.intent_summary = isHindi ? 'पेंशन की जानकारी' : 'Pension support';
    guide.reply = isHindi
      ? 'आपने ' + selectedState + ' चुना है। वृद्धावस्था, विधवा और दिव्यांग पेंशन के नियम अपने ज़िला समाज कल्याण कार्यालय से जाँचें। केंद्र और राज्य की योजनाएँ myScheme पर देखें।'
      : isTamil
        ? 'நீங்கள் ' + selectedState + '-ஐத் தேர்ந்தெடுத்துள்ளீர்கள். முதியோர், விதவை மற்றும் மாற்றுத்திறனாளி ஓய்வூதிய விதிகளை உங்கள் மாவட்ட சமூக நல அலுவலகத்தில் சரிபார்க்கவும். myScheme-ல் மத்திய மற்றும் மாநிலத் திட்டங்களைப் பார்க்கவும்.'
        : 'You selected ' + selectedState + '. Check old-age, widow, and disability pension rules with your district Social Welfare office. Browse central and state schemes on myScheme.';
    guide.next_steps = isHindi
      ? [selectedState + ' के ज़िला समाज कल्याण कार्यालय से पेंशन के बारे में पूछें।', 'myScheme पर केंद्र और राज्य की योजनाएँ देखें।', 'पात्रता और दस्तावेज़ की पुष्टि आधिकारिक कार्यालय से करें।']
      : isTamil
        ? [selectedState + ' மாவட்ட சமூக நல அலுவலகத்தில் ஓய்வூதிய உதவி கேளுங்கள்.', 'myScheme-ல் மத்திய மற்றும் மாநிலத் திட்டங்களைப் பாருங்கள்.', 'தகுதி மற்றும் ஆவணங்களை அதிகாரப்பூர்வ அலுவலகத்தில் உறுதிப்படுத்துங்கள்.']
        : [
          'Ask your ' + selectedState + ' district Social Welfare office about pension support.',
          'Browse central and state schemes on myScheme.',
          'Confirm eligibility and documents with an official office.',
        ];
    addSource('myScheme — Government of India', 'https://www.myscheme.gov.in/search');
    addSource('National Social Assistance Programme — Government of India', 'https://nsap.nic.in/');
  } else if (/pregnan|matern|mother|delivery|गर्भवती|गर्भ|मातृत्व|प्रसव/.test(text)) {
    guide.intent_summary = isHindi ? 'गर्भावस्था सहायता' : 'Maternity support';
    guide.reply = isHindi
      ? 'प्रधानमंत्री मातृ वंदना योजना (PMMVY) पात्र महिलाओं के लिए मातृत्व सहायता देती है। पहली संतान के लिए ₹5,000 और दूसरी संतान लड़की होने पर ₹6,000 का प्रावधान है। पात्रता और आवेदन की पुष्टि आंगनवाड़ी/आशा कार्यकर्ता या आधिकारिक पोर्टल से करें।'
      : 'Pradhan Mantri Matru Vandana Yojana (PMMVY) offers maternity support to eligible women: ₹5,000 for the first child and ₹6,000 for a second child if the child is a girl. Check eligibility and application steps with an Anganwadi/ASHA worker or the official portal.';
    guide.next_steps = isHindi
      ? ['नज़दीकी आंगनवाड़ी या आशा कार्यकर्ता से बात करें।', 'आधिकारिक PMMVY पोर्टल पर आवेदन की जानकारी देखें।', 'किसी से OTP या बैंक PIN साझा न करें।']
      : ['Speak with your nearest Anganwadi or ASHA worker.', 'Check application details on the official PMMVY portal.', 'Never share an OTP or bank PIN.'];
    guide.schemes.push(makeScheme(
      'Pradhan Mantri Matru Vandana Yojana (PMMVY)',
      '₹5,000 for the first child; ₹6,000 for a second child if the child is a girl.',
      'Maternity support for eligible pregnant and lactating women.',
      'Eligibility categories and conditions apply; confirm them with an Anganwadi/ASHA worker or the official portal.',
      'Visit the official PMMVY portal or ask an Anganwadi/ASHA worker to help.',
      'https://pmmvy.wcd.gov.in/',
    ));
    addSource('Ministry of Women and Child Development', 'https://wcd.gov.in/women/pradhan-mantri-matru-vandana-yojna');
  } else if (/ujjwala|lpg|gas cylinder|cooking gas|उज्ज्वला|गैस|सिलेंडर/.test(text)) {
    guide.intent_summary = isHindi ? 'गैस कनेक्शन सहायता' : 'LPG connection support';
    guide.reply = isHindi
      ? 'प्रधानमंत्री उज्ज्वला योजना के तहत पात्र गरीब परिवारों की वयस्क महिलाएँ नया LPG कनेक्शन लेने के लिए आवेदन कर सकती हैं। परिवार में पहले से LPG कनेक्शन नहीं होना चाहिए। नज़दीकी गैस वितरक से मदद लें या आधिकारिक वेबसाइट देखें।'
      : 'Under Pradhan Mantri Ujjwala Yojana, an adult woman in an eligible poor household may apply for a new LPG connection if the household has no existing LPG connection. Ask a nearby LPG distributor or use the official website.';
    guide.next_steps = isHindi
      ? ['नज़दीकी LPG वितरक से आवेदन में मदद माँगें।', 'ज़रूरी दस्तावेज़ आधिकारिक PMUY वेबसाइट पर देखें।', 'अपना OTP या बैंक PIN किसी को न बताएं।']
      : ['Ask a nearby LPG distributor for application help.', 'Check the required documents on the official PMUY website.', 'Never share your OTP or bank PIN.'];
    guide.schemes.push(makeScheme(
      'Pradhan Mantri Ujjwala Yojana (PMUY)',
      'A new LPG connection for eligible women in poor households.',
      'For an adult woman in a household without an existing LPG connection.',
      'Age, household eligibility, and documents must be confirmed on the official PMUY site or with a distributor.',
      'Apply online or visit an LPG distributor of your choice.',
      'https://www.pmuy.gov.in/ujjwala2.html',
    ));
    addSource('Pradhan Mantri Ujjwala Yojana — Government of India', 'https://www.pmuy.gov.in/');
  } else {
    guide.intent_summary = isHindi ? 'सरकारी मदद की खोज' : 'Finding government help';
    guide.reply = isHindi
      ? 'मैं बिना इंटरनेट कनेक्शन के कुछ सामान्य सरकारी योजनाओं की जानकारी दे सकती हूँ। पेंशन, गर्भावस्था सहायता या उज्ज्वला योजना के बारे में पूछें। किसी दूसरी योजना के लिए myScheme पर खोजें।'
      : 'I can give offline guidance for a few common government schemes: ask about pension, maternity support, or Ujjwala LPG connections. For other needs, search the Government of India’s myScheme directory.';
    guide.next_steps = isHindi
      ? ['अपनी ज़रूरत और राज्य का नाम लिखें।', 'myScheme की सरकारी योजना सूची देखें।']
      : ['Tell me what help you need and your state.', 'Browse the official myScheme directory.'];
    addSource('myScheme — Government of India', 'https://www.myscheme.gov.in/');
  }

  return guide;
}

function isOfflineTopic(message){
  return offlineDirectory.some(topic=>topic.match.test(message))||/pension|widow|old.?age|retirement|senior citizen|vridh|विधवा|पेंशन|बुढ़ापा|वृद्धावस्था|गर्भवती|गर्भ|मातृत्व|प्रसव|ujjwala|lpg|gas cylinder|cooking gas|उज्ज्वला|गैस|सिलेंडर/i.test(message);
}

window.DishaGuides = { offlineDirectory, createOfflineGuide, isOfflineTopic };
})();

