(function () {
// Text shown in the interface, grouped by language.
const copy = window.DishaTranslations = {
  hi:{eyebrow:'आपकी मदद, आपकी भाषा में',title:'किस काम में\nमदद चाहिए?',subtitle:'बोलकर या लिखकर बताइए। हम एक-एक कदम साथ चलेंगे।',micTitle:'बोलने के लिए छुएँ',micHint:'जैसे आप आम तौर पर बोलती हैं, वैसे बोलें',orType:'या यहाँ लिखें',inputLabel:'अपना सवाल लिखें',placeholder:'उदाहरण: मुझे विधवा पेंशन चाहिए',privacy:'आपका संदेश जवाब के लिए OpenAI को भेजा जाता है। आधार, OTP, PIN या बैंक की जानकारी साझा न करें।',quickTitle:'या कोई विषय चुनें',topicPension:'पेंशन और सहायता',topicHealth:'स्वास्थ्य सेवा',topicDocs:'मेरे दस्तावेज़',topicWork:'काम और कौशल',answerLabel:'आपके अगले कदम',officialCaption:'आगे की जानकारी सरकारी वेबसाइट पर मिलेगी।',trust:'सारी जानकारी यहीं देखें। सरकारी पेज आप चाहें तभी खोलें।',moreServices:'और सेवाएँ देखें ↗',footer:'शुरुआत करने में आपकी साथी',notGov:'यह सरकारी वेबसाइट नहीं है',listening:'सुन रही हूँ… अब बोलिए',voiceUnsupported:'इस ब्राउज़र में आवाज़ से लिखना उपलब्ध नहीं है। नीचे लिखकर बताइए।',noSpeech:'आवाज़ समझ नहीं आई। फिर कोशिश करें या लिखकर बताइए।',placeholderResponse:'अपनी बात लिखें या कोई विषय चुनें।',linkScheme:'सरकारी योजनाएँ देखें',linkServices:'सरकारी सेवाएँ देखें',pension:'पेंशन या आर्थिक सहायता',health:'स्वास्थ्य सहायता',documents:'ज़रूरी दस्तावेज़',work:'काम या नया कौशल',stepsScheme:['अपनी उम्र, राज्य और ज़रूरत के हिसाब से योजनाएँ खोजें।','जिस योजना में रुचि हो, उसकी पात्रता और ज़रूरी दस्तावेज़ देखें।','आवेदन का तरीका पढ़ें। कोई जानकारी समझ न आए तो यहाँ पूछें।'],stepsServices:['पहले अपनी ज़रूरत चुनें। सरकारी सेवा की सूची खुलेगी।','अपने राज्य या विभाग की सेवा ढूँढ़ें।','आगे बढ़ने से पहले फीस, दस्तावेज़ और आधिकारिक पते की जाँच करें।'],note:'पात्रता और नियम राज्य के अनुसार अलग हो सकते हैं। किसी को OTP, PIN या बैंक का पासवर्ड न बताएं।',sent:'आपका सवाल',tapTopic:'यह विषय चुना गया'},
  en:{eyebrow:'HELP, IN YOUR LANGUAGE',title:'What would you\nlike help with?',subtitle:'Say it or type it. We’ll take it one small step at a time.',micTitle:'Tap to speak',micHint:'Speak naturally, in your own words',orType:'OR TYPE HERE',inputLabel:'Type your question',placeholder:'For example: I need help finding a pension',privacy:'Your question and selected state are sent to OpenAI for an answer. Never share Aadhaar, OTP, PIN, or bank details.',quickTitle:'OR PICK A TOPIC',topicPension:'Pension & support',topicHealth:'Health care',topicDocs:'My documents',topicWork:'Work & skills',answerLabel:'YOUR NEXT STEPS',officialCaption:'Check the official page before you apply.',trust:'Read the details here. Open an official page only if you choose.',moreServices:'Explore services ↗',footer:'A friendly guide to getting started',notGov:'Not a government website',listening:'Listening… go ahead',voiceUnsupported:'Voice input is not available in this browser. You can type below.',noSpeech:'I didn’t catch that. Try again or type your question.',placeholderResponse:'Type what you need or choose a topic.',linkScheme:'Explore government schemes',linkServices:'Explore government services',pension:'Pension or financial support',health:'Health support',documents:'Important documents',work:'Work or learn a skill',stepsScheme:['Look for schemes based on your age, state, and what you need.','Open a scheme to check who can apply and which documents are needed.','Read how to apply. Ask here if any step is unclear.'],stepsServices:['Choose the kind of help you need to see government services.','Find the service for your state or department.','Before continuing, check the fee, documents, and official web address.'],note:'Eligibility and rules can vary by state. Never share your OTP, PIN, or banking password.',sent:'You asked',tapTopic:'You chose'},
  bn:{eyebrow:'আপনার ভাষায় আপনার সহায়ক',title:'কী বিষয়ে\nসাহায্য চান?',subtitle:'বলুন বা লিখুন। আমরা ধাপে ধাপে এগোব।',micTitle:'বলতে ট্যাপ করুন',micHint:'নিজের মতো করে স্বাভাবিকভাবে বলুন',orType:'অথবা এখানে লিখুন',inputLabel:'আপনার প্রশ্ন লিখুন',placeholder:'যেমন: পেনশন পেতে সাহায্য চাই',privacy:'এই ডেমোতে আপনার প্রশ্ন এই ডিভাইসেই থাকে।',quickTitle:'অথবা একটি বিষয় বেছে নিন',topicPension:'পেনশন ও সহায়তা',topicHealth:'স্বাস্থ্যসেবা',topicDocs:'আমার নথি',topicWork:'কাজ ও দক্ষতা',answerLabel:'আপনার পরবর্তী ধাপ',officialCaption:'পরের ধাপে সরকারি ওয়েবসাইটে যাবেন।',trust:'সহজ নির্দেশনা। সরকারি ওয়েবসাইটের লিঙ্ক।',moreServices:'সব পরিষেবা দেখুন ↗',footer:'শুরু করার সহায়ক সঙ্গী',notGov:'এটি সরকারি ওয়েবসাইট নয়',listening:'শুনছি… বলুন',voiceUnsupported:'এই ব্রাউজারে ভয়েস ইনপুট নেই। নিচে লিখে জানান।',noSpeech:'বুঝতে পারিনি। আবার বলুন বা লিখুন।',placeholderResponse:'আপনার প্রয়োজন লিখুন বা একটি বিষয় বেছে নিন।',linkScheme:'সরকারি প্রকল্প দেখুন',linkServices:'সরকারি পরিষেবা দেখুন',pension:'পেনশন বা আর্থিক সহায়তা',health:'স্বাস্থ্য সহায়তা',documents:'জরুরি নথি',work:'কাজ বা নতুন দক্ষতা',stepsScheme:['আপনার বয়স, রাজ্য ও প্রয়োজন অনুযায়ী প্রকল্প খুঁজুন।','কোন প্রকল্পে আবেদন করতে পারবেন এবং কী নথি লাগবে দেখুন।','আবেদনের পদ্ধতি পড়ুন। কিছু বুঝতে অসুবিধা হলে এখানে জিজ্ঞাসা করুন।'],stepsServices:['আপনার প্রয়োজন বেছে নিয়ে সরকারি পরিষেবার তালিকা দেখুন।','আপনার রাজ্য বা দপ্তরের পরিষেবাটি খুঁজুন।','চালিয়ে যাওয়ার আগে ফি, নথি এবং সরকারি ওয়েব ঠিকানা যাচাই করুন।'],note:'যোগ্যতা ও নিয়ম রাজ্যভেদে আলাদা হতে পারে। OTP, PIN বা ব্যাঙ্কের পাসওয়ার্ড কাউকে বলবেন না।',sent:'আপনার প্রশ্ন',tapTopic:'আপনি বেছে নিয়েছেন'},
  ta:{eyebrow:'உங்கள் மொழியில் உதவி',title:'எதில் உதவி\nவேண்டும்?',subtitle:'பேசுங்கள் அல்லது எழுதுங்கள். படிப்படியாகச் செய்வோம்.',micTitle:'பேசத் தொட தட்டவும்',micHint:'உங்கள் வழக்கமான பேச்சில் சொல்லுங்கள்',orType:'அல்லது இங்கே எழுதுங்கள்',inputLabel:'உங்கள் கேள்வியை எழுதுங்கள்',placeholder:'உதாரணம்: ஓய்வூதியம் பெற உதவி வேண்டும்',privacy:'இந்த மாதிரியில் உங்கள் கேள்வி இந்தச் சாதனத்தில் மட்டுமே இருக்கும்.',quickTitle:'அல்லது ஒரு தலைப்பைத் தேர்ந்தெடுக்கவும்',topicPension:'ஓய்வூதியம் & உதவி',topicHealth:'மருத்துவ சேவை',topicDocs:'என் ஆவணங்கள்',topicWork:'வேலை & திறன்கள்',answerLabel:'அடுத்த படிகள்',officialCaption:'அடுத்ததாக அரசு இணையதளத்திற்குச் செல்வீர்கள்.',trust:'எளிய வழிகாட்டல். அரசு இணையதள இணைப்புகள்.',moreServices:'சேவைகளைப் பார்க்க ↗',footer:'தொடங்க உதவும் தோழி',notGov:'இது அரசு இணையதளம் அல்ல',listening:'கேட்கிறேன்… சொல்லுங்கள்',voiceUnsupported:'இந்த உலாவியில் குரல் உள்ளீடு இல்லை. கீழே எழுதலாம்.',noSpeech:'புரியவில்லை. மீண்டும் முயற்சிக்கவும் அல்லது எழுதவும்.',placeholderResponse:'உங்கள் தேவையை எழுதுங்கள் அல்லது தலைப்பைத் தேர்ந்தெடுக்கவும்.',linkScheme:'அரசுத் திட்டங்களைப் பார்க்க',linkServices:'அரசு சேவைகளைப் பார்க்க',pension:'ஓய்வூதியம் அல்லது நிதி உதவி',health:'மருத்துவ உதவி',documents:'முக்கிய ஆவணங்கள்',work:'வேலை அல்லது திறன் பயிற்சி',stepsScheme:['வயது, மாநிலம் மற்றும் தேவைக்கேற்ப திட்டங்களைத் தேடுங்கள்.','விண்ணப்பிக்கத் தகுதி மற்றும் தேவையான ஆவணங்களைப் பாருங்கள்.','விண்ணப்பிக்கும் முறையைப் படியுங்கள். புரியவில்லை என்றால் இங்கே கேளுங்கள்.'],stepsServices:['தேவையைத் தேர்ந்தெடுத்து அரசு சேவைகளைப் பாருங்கள்.','உங்கள் மாநிலம் அல்லது துறைக்கான சேவையைக் கண்டறியுங்கள்.','தொடர்வதற்கு முன் கட்டணம், ஆவணங்கள், அரசு இணைய முகவரியைச் சரிபாருங்கள்.'],note:'தகுதி மற்றும் விதிகள் மாநிலத்துக்கு மாநிலம் மாறலாம். OTP, PIN அல்லது வங்கி கடவுச்சொல்லைப் பகிர வேண்டாம்.',sent:'உங்கள் கேள்வி',tapTopic:'நீங்கள் தேர்ந்தெடுத்தது'},
  te:{eyebrow:'మీ భాషలో మీకు సహాయం',title:'దేనిలో సహాయం\nకావాలి?',subtitle:'చెప్పండి లేదా టైప్ చేయండి. ఒక్కో అడుగు కలిసి చేద్దాం.',micTitle:'మాట్లాడటానికి నొక్కండి',micHint:'మీకు సహజంగా అనిపించినట్లు చెప్పండి',orType:'లేదా ఇక్కడ టైప్ చేయండి',inputLabel:'మీ ప్రశ్న టైప్ చేయండి',placeholder:'ఉదాహరణ: పెన్షన్ పొందడంలో సహాయం కావాలి',privacy:'ఈ డెమోలో మీ ప్రశ్న ఈ పరికరంలోనే ఉంటుంది.',quickTitle:'లేదా ఒక అంశాన్ని ఎంచుకోండి',topicPension:'పెన్షన్ & సహాయం',topicHealth:'ఆరోగ్య సేవ',topicDocs:'నా పత్రాలు',topicWork:'పని & నైపుణ్యాలు',answerLabel:'తదుపరి అడుగులు',officialCaption:'తర్వాత ప్రభుత్వ వెబ్‌సైట్‌లో కొనసాగుతారు.',trust:'సులభమైన సూచనలు. అధికారిక ప్రభుత్వ లింకులు.',moreServices:'సేవలను చూడండి ↗',footer:'ప్రారంభించేందుకు మీ తోడు',notGov:'ఇది ప్రభుత్వ వెబ్‌సైట్ కాదు',listening:'వింటున్నాను… చెప్పండి',voiceUnsupported:'ఈ బ్రౌజర్‌లో వాయిస్ ఇన్‌పుట్ లేదు. కింద టైప్ చేయవచ్చు.',noSpeech:'అర్థం కాలేదు. మళ్లీ ప్రయత్నించండి లేదా టైప్ చేయండి.',placeholderResponse:'మీకు కావాల్సింది టైప్ చేయండి లేదా అంశాన్ని ఎంచుకోండి.',linkScheme:'ప్రభుత్వ పథకాలను చూడండి',linkServices:'ప్రభుత్వ సేవలను చూడండి',pension:'పెన్షన్ లేదా ఆర్థిక సహాయం',health:'ఆరోగ్య సహాయం',documents:'ముఖ్యమైన పత్రాలు',work:'పని లేదా నైపుణ్యం నేర్చుకోండి',stepsScheme:['మీ వయసు, రాష్ట్రం, అవసరానికి సరిపోయే పథకాలను వెతకండి.','అర్హత, అవసరమైన పత్రాలు తెలుసుకోవడానికి పథకాన్ని తెరవండి.','దరఖాస్తు విధానం చదవండి. అర్థం కానిది ఉంటే ఇక్కడ అడగండి.'],stepsServices:['మీ అవసరాన్ని ఎంచుకుని ప్రభుత్వ సేవలను చూడండి.','మీ రాష్ట్రం లేదా శాఖకు సంబంధించిన సేవను కనుగొనండి.','కొనసాగేముందు రుసుము, పత్రాలు, అధికారిక చిరునామా తనిఖీ చేయండి.'],note:'అర్హత, నియమాలు రాష్ట్రాన్ని బట్టి మారవచ్చు. OTP, PIN, బ్యాంక్ పాస్‌వర్డ్‌ను ఎవరితోనూ పంచుకోవద్దు.',sent:'మీ ప్రశ్న',tapTopic:'మీరు ఎంచుకున్నది'},
  mr:{eyebrow:'तुमच्या भाषेत तुमची मदतनीस',title:'कशासाठी मदत\nहवी आहे?',subtitle:'बोलून किंवा लिहून सांगा. आपण एकेक पाऊल घेऊ.',micTitle:'बोलण्यासाठी टॅप करा',micHint:'तुम्ही नेहमी बोलता तसे सांगा',orType:'किंवा इथे लिहा',inputLabel:'तुमचा प्रश्न लिहा',placeholder:'उदाहरण: मला पेन्शन मिळवण्यासाठी मदत हवी',privacy:'या डेमोमध्ये तुमचा प्रश्न याच डिव्हाइसवर राहतो.',quickTitle:'किंवा एक विषय निवडा',topicPension:'पेन्शन आणि मदत',topicHealth:'आरोग्य सेवा',topicDocs:'माझी कागदपत्रे',topicWork:'काम आणि कौशल्ये',answerLabel:'पुढची पावले',officialCaption:'पुढे सरकारी वेबसाइटवर जाल.',trust:'सोपे मार्गदर्शन. सरकारी वेबसाइटचे दुवे.',moreServices:'सेवा पाहा ↗',footer:'सुरुवात करण्यासाठी तुमची सोबती',notGov:'ही सरकारी वेबसाइट नाही',listening:'ऐकत आहे… बोला',voiceUnsupported:'या ब्राउझरमध्ये आवाजाने लिहिता येत नाही. खाली टाइप करा.',noSpeech:'समजले नाही. पुन्हा प्रयत्न करा किंवा टाइप करा.',placeholderResponse:'तुमची गरज टाइप करा किंवा विषय निवडा.',linkScheme:'सरकारी योजना पाहा',linkServices:'सरकारी सेवा पाहा',pension:'पेन्शन किंवा आर्थिक मदत',health:'आरोग्य मदत',documents:'महत्त्वाची कागदपत्रे',work:'काम किंवा कौशल्य शिका',stepsScheme:['वय, राज्य आणि गरजेनुसार योजना शोधा.','योजनेसाठी पात्रता आणि आवश्यक कागदपत्रे तपासा.','अर्ज कसा करायचा ते वाचा. काही समजले नाही तर इथे विचारा.'],stepsServices:['तुमची गरज निवडून सरकारी सेवा पाहा.','तुमच्या राज्याची किंवा विभागाची सेवा शोधा.','पुढे जाण्यापूर्वी शुल्क, कागदपत्रे आणि सरकारी पत्ता तपासा.'],note:'पात्रता आणि नियम राज्यानुसार वेगळे असू शकतात. OTP, PIN किंवा बँकेचा पासवर्ड कोणालाही सांगू नका.',sent:'तुमचा प्रश्न',tapTopic:'तुम्ही निवडले'},
};
// Starter translations for the other scheduled Indian languages. Keep the main
// prompts, topic choices and next-step headings in the selected script; English
// remains the fallback for detailed guidance where the demo has no translation.
const extraCopy={
  as:{eyebrow:'আপোনাৰ ভাষাত আপোনাৰ সহায়ক',title:'কিহত সহায়\nলাগিব?',subtitle:'কওক বা লিখক। আমি ধাপে ধাপে আগবাঢ়িম।',micTitle:'ক’বলৈ টিপক',micHint:'নিজৰ ভাষাত স্বাভাৱিকভাৱে কওক',orType:'নহ’লে ইয়াত লিখক',placeholder:'উদাহৰণ: পেঞ্চন বিচাৰি সহায় লাগে',quickTitle:'নহ’লে এটা বিষয় বাছক',topicPension:'পেঞ্চন আৰু সহায়',topicHealth:'স্বাস্থ্য সেৱা',topicDocs:'মোৰ নথিপত্ৰ',topicWork:'কাম আৰু দক্ষতা',answerLabel:'আপোনাৰ পৰৱৰ্তী পদক্ষেপ',footer:'আৰম্ভ কৰিবলৈ আপোনাৰ সংগী',notGov:'এইটো চৰকাৰী ৱেবছাইট নহয়'},
  brx:{eyebrow:'नोंथांनि रावजों मदद',title:'मा मदद\nनांगौ?',subtitle:'बुंनो एबा लिरनो। जों खेब खेब मदद होगोन।',micTitle:'बुंनो थांनायखौ दब',micHint:'नोंथांनि रावजों बुं',orType:'एबा बेयाव लिर',placeholder:'जेरै: पेन्सननि मदद नांगौ',quickTitle:'एबा मोनसे बिसय सायख',topicPension:'पेन्सन आरो मदद',topicHealth:'आरोमगिरि सेवा',topicDocs:'आंनि फोरमान बिलाइ',topicWork:'खामानि आरो सोलोंनाय',answerLabel:'नोंथांनि उननि खेब',footer:'गुबै खेब मदद',notGov:'बेयो सरकारि वेबसाइट नङा'},
  doi:{eyebrow:'तुंदी भाशा च मदद',title:'कुस चीजै च\nमदद चाहिदी?',subtitle:'बोलो जां लिखो। अस इक-इक कदम चलगे।',micTitle:'बोलने आस्तै दबाओ',micHint:'अपनी भाशा च बोलो',orType:'जां इत्थै लिखो',placeholder:'मिसाल: पेंशन लेई मदद चाहीदी',quickTitle:'जां इक विषय चुनो',topicPension:'पेंशन ते मदद',topicHealth:'सेहत सेवा',topicDocs:'मेरे दस्तावेज़',topicWork:'कम्म ते हुनर',answerLabel:'अगले कदम',footer:'शुरुआत च तुंदी साथी',notGov:'एह सरकारी वेबसाइट नेईं ऐ'},
  gu:{eyebrow:'તમારી ભાષામાં તમારી મદદગાર',title:'શામાં મદદ\nજોઈએ છે?',subtitle:'બોલો અથવા લખો. આપણે એક પછી એક પગલું લઈશું.',micTitle:'બોલવા માટે ટૅપ કરો',micHint:'તમારી ભાષામાં સહજ રીતે બોલો',orType:'અથવા અહીં લખો',placeholder:'ઉદાહરણ: પેન્શન મેળવવામાં મદદ જોઈએ',quickTitle:'અથવા વિષય પસંદ કરો',topicPension:'પેન્શન અને સહાય',topicHealth:'આરોગ્ય સેવા',topicDocs:'મારા દસ્તાવેજો',topicWork:'કામ અને કૌશલ્ય',answerLabel:'આગળનાં પગલાં',footer:'શરૂઆત માટે તમારી સાથી',notGov:'આ સરકારી વેબસાઇટ નથી'},
  kn:{eyebrow:'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ನಿಮ್ಮ ಸಹಾಯಕಿ',title:'ಯಾವ ವಿಷಯದಲ್ಲಿ\nಸಹಾಯ ಬೇಕು?',subtitle:'ಮಾತನಾಡಿ ಅಥವಾ ಬರೆಯಿರಿ. ಒಂದೊಂದೇ ಹೆಜ್ಜೆ ಮುಂದೆ ಹೋಗೋಣ.',micTitle:'ಮಾತನಾಡಲು ಒತ್ತಿ',micHint:'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಸಹಜವಾಗಿ ಮಾತನಾಡಿ',orType:'ಅಥವಾ ಇಲ್ಲಿ ಬರೆಯಿರಿ',placeholder:'ಉದಾಹರಣೆ: ಪಿಂಚಣಿ ಪಡೆಯಲು ಸಹಾಯ ಬೇಕು',quickTitle:'ಅಥವಾ ವಿಷಯ ಆಯ್ಕೆಮಾಡಿ',topicPension:'ಪಿಂಚಣಿ ಮತ್ತು ನೆರವು',topicHealth:'ಆರೋಗ್ಯ ಸೇವೆ',topicDocs:'ನನ್ನ ದಾಖಲೆಗಳು',topicWork:'ಕೆಲಸ ಮತ್ತು ಕೌಶಲ್ಯ',answerLabel:'ಮುಂದಿನ ಹಂತಗಳು',footer:'ಆರಂಭಿಸಲು ನಿಮ್ಮ ಜೊತೆಗಾರ್ತಿ',notGov:'ಇದು ಸರ್ಕಾರಿ ವೆಬ್‌ಸೈಟ್ ಅಲ್ಲ'},
  ks:{eyebrow:'تُہندِ زَبانہٕ مَنٛز مدد',title:'کِتھ پٲٹھۍ مدد\nضرورت چھِ?',subtitle:'وُچھِو یا لیکھو۔ اَسۍ قدم بہ قدم گژھَو۔',micTitle:'وُنُن خٲطرٕ ٹَپ کٔرِو',micHint:'پنٛنہِ زَبانہٕ مَنٛز وُچھِو',orType:'یا یَتھ لیکھو',placeholder:'مثال: پنشن خٲطرٕ مدد چھِٚیہ',quickTitle:'یا اَکھ موضوع ژٲریو',topicPension:'پنشن تہٕ مدد',topicHealth:'صحت سروس',topicDocs:'مےٚ دستاویز',topicWork:'کام تہٕ ہُنر',answerLabel:'اَگلے قدم',footer:'شروعات خٲطرٕ مددگار',notGov:'یہِ سرکاری ویب سائٹ چھِ نَہ'},
  kok:{eyebrow:'तुमच्या भाशेंत तुमची मदत',title:'खंयच्या कामाक\nमदत जाय?',subtitle:'उलोवचें वा बरयचें. एकेक पावलान वचूंया.',micTitle:'उलोवपाक टॅप करात',micHint:'तुमच्या भाशेंत उलोवचें',orType:'वा हांगा बरयात',placeholder:'उदाहरण: पेन्शनाक मदत जाय',quickTitle:'वा विशय वेंचात',topicPension:'पेन्शन आनी आदार',topicHealth:'आरोग्य सेवा',topicDocs:'म्हजीं कागदां',topicWork:'काम आनी कौशल्य',answerLabel:'फुडलीं पावलां',footer:'सुरवातीक तुमची सोबती',notGov:'हें सरकारी संकेतथळ न्हय'},
  mai:{eyebrow:'अहाँक भाषामे अहाँक सहायक',title:'कोन काजमे\nमदति चाही?',subtitle:'बोलू वा लिखू। हम एक-एकटा कदम संग चलब।',micTitle:'बजबाक लेल छूबू',micHint:'अपन भाषामे सहज रूपेँ बाजू',orType:'अथवा एतय लिखू',placeholder:'जेना: पेंशन लेल मदति चाही',quickTitle:'अथवा विषय चुनू',topicPension:'पेंशन आ सहायता',topicHealth:'स्वास्थ्य सेवा',topicDocs:'हमर कागजात',topicWork:'काज आ कौशल',answerLabel:'आगू के कदम',footer:'शुरुआत लेल अहाँक संगी',notGov:'ई सरकारी वेबसाइट नहि अछि'},
  ml:{eyebrow:'നിങ്ങളുടെ ഭാഷയിൽ സഹായം',title:'എന്തിലാണ്\nസഹായം വേണ്ടത്?',subtitle:'പറയുകയോ എഴുതുകയോ ചെയ്യൂ. ഓരോ ചുവടും ഒരുമിച്ച് നോക്കാം.',micTitle:'സംസാരിക്കാൻ തൊടുക',micHint:'നിങ്ങളുടെ ഭാഷയിൽ സ്വാഭാവികമായി പറയൂ',orType:'അല്ലെങ്കിൽ ഇവിടെ എഴുതൂ',placeholder:'ഉദാഹരണം: പെൻഷൻ ലഭിക്കാൻ സഹായം വേണം',quickTitle:'അല്ലെങ്കിൽ വിഷയം തിരഞ്ഞെടുക്കൂ',topicPension:'പെൻഷനും സഹായവും',topicHealth:'ആരോഗ്യ സേവനം',topicDocs:'എന്റെ രേഖകൾ',topicWork:'ജോലിയും നൈപുണ്യവും',answerLabel:'അടുത്ത ഘട്ടങ്ങൾ',footer:'തുടങ്ങാൻ നിങ്ങളുടെ കൂട്ടുകാരി',notGov:'ഇത് സർക്കാർ വെബ്സൈറ്റ് അല്ല'},
  mni:{eyebrow:'ꯅꯪꯒꯤ ꯂꯣꯟꯗ ꯃꯇꯦꯡ',title:'ꯀꯔꯝꯕ ꯃꯇꯦꯡ\nꯄꯥꯝꯕꯒꯦ?',subtitle:'ꯋꯥꯍꯪ ꯄꯤꯌꯨ ꯅꯠꯔꯒ ꯏꯌꯨ। ꯑꯃꯝꯕ ꯑꯃꯝꯕ ꯂꯝꯖꯤꯡꯒꯅꯤ।',micTitle:'ꯋꯥꯍꯪ ꯄꯤꯅꯕ ꯇꯞ ꯇꯧ',micHint:'ꯅꯪꯒꯤ ꯂꯣꯟꯗ ꯋꯥꯍꯪ ꯄꯤꯌꯨ',orType:'ꯅꯠꯔꯒ ꯃꯐꯝꯁꯤꯗ ꯏꯌꯨ',placeholder:'ꯃꯁꯥꯜ: ꯄꯦꯟꯁꯟꯒꯤ ꯃꯇꯦꯡ ꯄꯥꯝꯃꯤ',quickTitle:'ꯅꯠꯔꯒ ꯃꯔꯣꯝ ꯑꯃ ꯈꯜꯂꯨ',topicPension:'ꯄꯦꯟꯁꯟ ꯑꯃꯁꯨꯡ ꯃꯇꯦꯡ',topicHealth:'ꯑꯔꯣꯒꯌ ꯁꯔꯚꯤꯁ',topicDocs:'ꯑꯩꯒꯤ ꯄꯥꯎꯖꯦꯜ',topicWork:'ꯊꯕꯛ ꯑꯃꯁꯨꯡ ꯁꯛꯇꯝ',answerLabel:'ꯃꯊꯪꯒꯤ ꯂꯝꯖꯤꯡ',footer:'ꯍꯧꯅꯕ ꯅꯪꯒꯤ ꯃꯇꯦꯡ',notGov:'ꯃꯁꯤ ꯁꯔꯀꯥꯔꯒꯤ ꯋꯦꯕꯁꯥꯏꯠ ꯅꯠꯇꯦ'},
  ne:{eyebrow:'तपाईंको भाषामा तपाईंको सहयोगी',title:'के कुरामा\nसहयोग चाहिन्छ?',subtitle:'भन्नुहोस् वा लेख्नुहोस्। हामी एकएक पाइला सँगै चाल्नेछौँ।',micTitle:'बोल्न थिच्नुहोस्',micHint:'आफ्नो भाषामा स्वाभाविक रूपमा भन्नुहोस्',orType:'वा यहाँ लेख्नुहोस्',placeholder:'उदाहरण: पेन्सन पाउन सहयोग चाहियो',quickTitle:'वा एउटा विषय छान्नुहोस्',topicPension:'पेन्सन र सहयोग',topicHealth:'स्वास्थ्य सेवा',topicDocs:'मेरा कागजात',topicWork:'काम र सीप',answerLabel:'अबका चरणहरू',footer:'सुरु गर्न तपाईंको साथी',notGov:'यो सरकारी वेबसाइट होइन'},
  or:{eyebrow:'ଆପଣଙ୍କ ଭାଷାରେ ସହାୟତା',title:'କେଉଁଥିରେ\nସହାୟତା ଦରକାର?',subtitle:'କୁହନ୍ତୁ କିମ୍ବା ଲେଖନ୍ତୁ। ଆମେ ଧୀରେ ଧୀରେ ଆଗେଇବା।',micTitle:'କହିବାକୁ ଟ୍ୟାପ୍ କରନ୍ତୁ',micHint:'ନିଜ ଭାଷାରେ ସ୍ୱାଭାବିକ ଭାବେ କୁହନ୍ତୁ',orType:'ନହେଲେ ଏଠାରେ ଲେଖନ୍ତୁ',placeholder:'ଉଦାହରଣ: ପେନ୍‌ସନ୍ ପାଇଁ ସହାୟତା ଦରକାର',quickTitle:'ନହେଲେ ଏକ ବିଷୟ ବାଛନ୍ତୁ',topicPension:'ପେନ୍‌ସନ୍ ଓ ସହାୟତା',topicHealth:'ସ୍ୱାସ୍ଥ୍ୟ ସେବା',topicDocs:'ମୋର ଦଲିଲ',topicWork:'କାମ ଓ ଦକ୍ଷତା',answerLabel:'ପରବର୍ତ୍ତୀ ପଦକ୍ଷେପ',footer:'ଆରମ୍ଭ ପାଇଁ ଆପଣଙ୍କ ସାଥୀ',notGov:'ଏହା ସରକାରୀ ୱେବସାଇଟ୍ ନୁହେଁ'},
  pa:{eyebrow:'ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ ਤੁਹਾਡੀ ਸਹਾਇਕ',title:'ਕਿਸ ਕੰਮ ਲਈ\nਮਦਦ ਚਾਹੀਦੀ ਹੈ?',subtitle:'ਬੋਲੋ ਜਾਂ ਲਿਖੋ। ਅਸੀਂ ਇੱਕ-ਇੱਕ ਕਦਮ ਨਾਲ ਚੱਲਾਂਗੇ।',micTitle:'ਬੋਲਣ ਲਈ ਛੂਹੋ',micHint:'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਕੁਦਰਤੀ ਤਰੀਕੇ ਨਾਲ ਬੋਲੋ',orType:'ਜਾਂ ਇੱਥੇ ਲਿਖੋ',placeholder:'ਉਦਾਹਰਨ: ਪੈਨਸ਼ਨ ਲਈ ਮਦਦ ਚਾਹੀਦੀ ਹੈ',quickTitle:'ਜਾਂ ਕੋਈ ਵਿਸ਼ਾ ਚੁਣੋ',topicPension:'ਪੈਨਸ਼ਨ ਅਤੇ ਮਦਦ',topicHealth:'ਸਿਹਤ ਸੇਵਾ',topicDocs:'ਮੇਰੇ ਦਸਤਾਵੇਜ਼',topicWork:'ਕੰਮ ਅਤੇ ਹੁਨਰ',answerLabel:'ਤੁਹਾਡੇ ਅਗਲੇ ਕਦਮ',footer:'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਤੁਹਾਡੀ ਸਾਥੀ',notGov:'ਇਹ ਸਰਕਾਰੀ ਵੈੱਬਸਾਈਟ ਨਹੀਂ ਹੈ'},
  sa:{eyebrow:'भवत्याः भाषायां सहायिका',title:'कस्मिन् विषये\nसाहाय्यं अपेक्षितम्?',subtitle:'वदतु अथवा लिखतु। वयं शनैः शनैः अग्रे गच्छामः।',micTitle:'वक्तुं स्पृशतु',micHint:'स्वभाषया सहजतया वदतु',orType:'अथवा अत्र लिखतु',placeholder:'उदाहरणम्: निवृत्तिवेतनाय साहाय्यम् इच्छामि',quickTitle:'अथवा विषयं चिनोतु',topicPension:'निवृत्तिवेतनं च सहायता',topicHealth:'आरोग्यसेवा',topicDocs:'मम प्रमाणपत्राणि',topicWork:'कार्यं च कौशलम्',answerLabel:'अग्रिमानि सोपानानि',footer:'आरम्भाय भवत्याः सहायिका',notGov:'एतत् शासकीयजालपुटं नास्ति'},
  sat:{eyebrow:'आमाक् पा़रसी रे गोड़ो',title:'ओका काज रे\nगोड़ो ला़कतीया?',subtitle:'रोड़ मे या ओल मे। आलो ञेपते ञेपते सेनोक् आ।',micTitle:'रोड़ ला़गित् दबाव मे',micHint:'आमाक् पा़रसी रे रोड़ मे',orType:'आर बाङखान नोड़े ओल मे',placeholder:'जोनोका: पेंशन ला़गित् गोड़ो ला़कतीया',quickTitle:'आर बाङखान मित् बिसय बाछाव मे',topicPension:'पेंशन आर गोड़ो',topicHealth:'सुसाथिया सेवा',topicDocs:'आमाक् कागोज को',topicWork:'का़मी आर हुनार',answerLabel:'इना़ तायोमाक् धाप को',footer:'एहोब ला़गित् आमाक् सोबति',notGov:'नोवा सोरकार रेयाक् वेबसाइट बाङकाना'},
  sd:{eyebrow:'اوهان جي ٻوليءَ ۾ مدد',title:'ڪهڙي ڪم ۾\nمدد گهرجي؟',subtitle:'ڳالهايو يا لکو. اچو ته هڪ هڪ قدم کڻون.',micTitle:'ڳالهائڻ لاءِ ٽيپ ڪريو',micHint:'پنهنجي ٻوليءَ ۾ عام نموني ڳالهايو',orType:'يا هتي لکو',placeholder:'مثال: پينشن لاءِ مدد گهرجي',quickTitle:'يا هڪ موضوع چونڊيو',topicPension:'پينشن ۽ مدد',topicHealth:'صحت جي سهولت',topicDocs:'منهنجا دستاويز',topicWork:'ڪم ۽ هنر',answerLabel:'اڳيان قدم',footer:'شروعات لاءِ اوهان جي ساٿي',notGov:'هي سرڪاري ويب سائيٽ ناهي'},
  ur:{eyebrow:'آپ کی زبان میں آپ کی مددگار',title:'کس کام میں\nمدد چاہیے؟',subtitle:'بولیں یا لکھیں۔ ہم ایک ایک قدم ساتھ چلیں گے۔',micTitle:'بولنے کے لیے دبائیں',micHint:'اپنی زبان میں عام انداز سے بولیں',orType:'یا یہاں لکھیں',placeholder:'مثال: پنشن حاصل کرنے میں مدد چاہیے',quickTitle:'یا کوئی موضوع منتخب کریں',topicPension:'پنشن اور مدد',topicHealth:'صحت کی سہولت',topicDocs:'میرے دستاویزات',topicWork:'کام اور ہنر',answerLabel:'اگلے مراحل',footer:'شروعات کے لیے آپ کی ساتھی',notGov:'یہ سرکاری ویب سائٹ نہیں ہے'}
};
Object.assign(copy,extraCopy);
const privacyByLocale={
  as:'আপোনাৰ বাৰ্তা উত্তৰৰ বাবে OpenAI-লৈ পঠিওৱা হয়। আধাৰ, OTP, PIN বা বেংকৰ তথ্য নিদিব।',
  bn:'আপনার বার্তা উত্তরের জন্য OpenAI-তে পাঠানো হয়। আধার, OTP, PIN বা ব্যাঙ্কের তথ্য দেবেন না।',
  brx:'नोंथांनि बुंथाइखौ फिननायनि थाखाय OpenAI आव दैथायो। Aadhaar, OTP, PIN एबा बैंकनि फोरमायथिहोग्रा होनो नाङा।',
  doi:'तुंदा संदेश जवाब आस्तै OpenAI गी भेजेआ जंदा ऐ। आधार, OTP, PIN जां बैंक दी जानकारी नेईं देओ।',
  en:'Your message and recent chat are sent to OpenAI for an answer. Never share Aadhaar, OTP, PIN, passwords, or bank details.',
  gu:'તમારો સંદેશ જવાબ માટે OpenAIને મોકલાય છે. આધાર, OTP, PIN કે બેંકની વિગતો ક્યારેય આપશો નહીં.',
  hi:'आपका संदेश और हाल की बातचीत जवाब के लिए OpenAI को भेजी जाती है। आधार, OTP, PIN, पासवर्ड या बैंक की जानकारी साझा न करें।',
  kn:'ನಿಮ್ಮ ಸಂದೇಶ ಮತ್ತು ಇತ್ತೀಚಿನ ಮಾತುಕತೆಯನ್ನು ಉತ್ತರಕ್ಕಾಗಿ OpenAIಗೆ ಕಳುಹಿಸಲಾಗುತ್ತದೆ. ಆಧಾರ್, OTP, PIN, ಪಾಸ್‌ವರ್ಡ್ ಅಥವಾ ಬ್ಯಾಂಕ್ ವಿವರಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಬೇಡಿ.',
  kok:'तुमचो संदेश आनी निमाणें संवाद जाप दिवपाखातीर OpenAI कडेन धाडटा. आधार, OTP, PIN, पासवर्ड वा बँकेची म्हायती दिवंक नाका.',
  mai:'अहाँक संदेश आ हालक बातचीतक जवाब लेल OpenAI लग पठाओल जाइत अछि। आधार, OTP, PIN, पासवर्ड वा बैंकक जानकारी नहि दिअ।',
  ml:'നിങ്ങളുടെ സന്ദേശവും അടുത്തിടെയുള്ള സംഭാഷണവും മറുപടിക്കായി OpenAI-ലേക്ക് അയയ്ക്കും. ആധാർ, OTP, PIN, പാസ്‌വേഡ്, ബാങ്ക് വിവരങ്ങൾ പങ്കിടരുത്.',
  mr:'तुमचा संदेश आणि अलीकडील संवाद उत्तरासाठी OpenAI कडे पाठवला जातो. आधार, OTP, PIN, पासवर्ड किंवा बँकेची माहिती देऊ नका.',
  ne:'तपाईंको सन्देश र हालको कुराकानी जवाफका लागि OpenAI मा पठाइन्छ। आधार, OTP, PIN, पासवर्ड वा बैंक विवरण नदिनुहोस्।',
  or:'ଆପଣଙ୍କ ବାର୍ତ୍ତା ଓ ସାମ୍ପ୍ରତିକ କଥାବାର୍ତ୍ତା ଉତ୍ତର ପାଇଁ OpenAIକୁ ପଠାଯାଏ। ଆଧାର, OTP, PIN, ପାସୱାର୍ଡ କିମ୍ବା ବ୍ୟାଙ୍କ ତଥ୍ୟ ଦିଅନ୍ତୁ ନାହିଁ।',
  pa:'ਤੁਹਾਡਾ ਸੁਨੇਹਾ ਅਤੇ ਹਾਲੀਆ ਗੱਲਬਾਤ ਜਵਾਬ ਲਈ OpenAI ਨੂੰ ਭੇਜੀ ਜਾਂਦੀ ਹੈ। ਆਧਾਰ, OTP, PIN, ਪਾਸਵਰਡ ਜਾਂ ਬੈਂਕ ਦੀ ਜਾਣਕਾਰੀ ਨਾ ਦਿਓ।',
  ta:'உங்கள் செய்தியும் சமீபத்திய உரையாடலும் பதிலுக்காக OpenAI-க்கு அனுப்பப்படும். ஆதார், OTP, PIN, கடவுச்சொல் அல்லது வங்கி விவரங்களைப் பகிர வேண்டாம்.',
  te:'మీ సందేశం, ఇటీవలి సంభాషణ సమాధానం కోసం OpenAIకి పంపబడతాయి. ఆధార్, OTP, PIN, పాస్‌వర్డ్ లేదా బ్యాంకు వివరాలు పంచుకోవద్దు.',
  ur:'آپ کا پیغام اور حالیہ گفتگو جواب کے لیے OpenAI کو بھیجی جاتی ہے۔ آدھار، OTP، PIN، پاس ورڈ یا بینک کی معلومات نہ دیں。',
};
for(const [locale,line] of Object.entries(privacyByLocale))if(copy[locale])copy[locale].privacy=line;
const schemeLinkByLocale={
  as:'চৰকাৰী আঁচনি বিচাৰক',brx:'सोरखारि स्किम नाय',doi:'सरकारी स्कीम दिक्खो',gu:'સરકારી યોજનાઓ જુઓ',kn:'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ನೋಡಿ',ks:'سرکاری اسکیمہ وٲچھِو',kok:'सरकारी येवजण्यो पळयात',mai:'सरकारी योजना देखू',ml:'സർക്കാർ പദ്ധതികൾ കാണുക',mni:'ꯁꯔꯀꯥꯔꯒꯤ ꯁꯤꯝꯁꯤꯡ ꯌꯦꯡꯉꯨ',ne:'सरकारी योजनाहरू हेर्नुहोस्',or:'ସରକାରୀ ଯୋଜନା ଦେଖନ୍ତୁ',pa:'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਵੇਖੋ',sa:'शासकीययोजनाः पश्यन्तु',sat:'सोरकारि स्किम को ञेल मे',sd:'سرڪاري رٿائون ڏسو',ur:'سرکاری اسکیمیں دیکھیں'
};
for(const [locale,label] of Object.entries(schemeLinkByLocale))if(copy[locale])copy[locale].linkScheme=label;
const newUiDefaults={stateLabel:'YOUR STATE / UT',brandCaption:'GOVERNMENT HELP, MADE HUMAN',safeTitle:'Keep your information safe',askLabel:'ASK DISHA',askTitle:'What kind of help are you looking for?',searchHint:'Search official sources · get an answer in your language',offlineHint:'Offline guide ready · common government services',offlinePrivacy:'Offline questions stay on this device. Never share Aadhaar, OTP, PIN, passwords, or bank details.',browseMore:'Browse all help topics',setupFile:'To get answers, start Disha and open http://127.0.0.1:4173 (not this saved file).',setupKey:'Disha is running, but its AI key is not set. Add OPENAI_API_KEY to the .env file and restart Disha.',setupServer:'Disha’s local service is not running. Start it with “npm start”, then open http://127.0.0.1:4173.',sourcesTitle:'OFFICIAL SOURCES',verifiedLabel:'Sources are checked'};
for(const locale of Object.values(copy))Object.assign(locale,newUiDefaults);
for(const locale of Object.values(copy))locale.trust='Read the scheme details here. Open an official page only if you choose.';
Object.assign(copy.hi,{brandCaption:'सरकारी मदद, आपकी भाषा में',safeTitle:'अपनी जानकारी सुरक्षित रखें',askLabel:'दिशा से पूछें',askTitle:'आपको किस मदद की तलाश है?',searchHint:'सरकारी स्रोतों में खोजेगा · आपकी भाषा में जवाब देगा',sourcesTitle:'आधिकारिक स्रोत',verifiedLabel:'स्रोत जाँचे जाते हैं'});
Object.assign(copy.hi,{offlineHint:'बिना इंटरनेट भी मदद मिलेगी · सरकारी सेवाओं के बारे में पूछें',offlinePrivacy:'बिना इंटरनेट वाले सवाल इसी डिवाइस पर रहते हैं। आधार, OTP, PIN या बैंक की जानकारी साझा न करें।',browseMore:'सभी मदद के विषय देखें',setupFile:'जवाब पाने के लिए Disha चालू करें और http://127.0.0.1:4173 खोलें। यह सेव की हुई फ़ाइल है, यहाँ जवाब नहीं मिलेंगे।',setupKey:'Disha चल रहा है, लेकिन AI key सेट नहीं है। .env फ़ाइल में OPENAI_API_KEY जोड़कर Disha फिर से शुरू करें।',setupServer:'Disha सेवा नहीं चल रही। “npm start” से शुरू करें, फिर http://127.0.0.1:4173 खोलें।'});
copy.hi.trust='योजना की जानकारी यहीं पढ़ें। सरकारी पेज आप चाहें तभी खोलें।';
copy.hi.stateLabel='आपका राज्य / केंद्र शासित प्रदेश';
copy.hi.privacy='आपका सवाल और चुना हुआ राज्य जवाब के लिए OpenAI को भेजा जाता है। आधार, OTP, PIN या बैंक की जानकारी साझा न करें।';
Object.assign(copy.bn,{brandCaption:'সরকারি সহায়তা, আপনার ভাষায়',safeTitle:'আপনার তথ্য নিরাপদ রাখুন',askLabel:'দিশাকে জিজ্ঞাসা করুন',askTitle:'আপনি কী ধরনের সাহায্য খুঁজছেন?',searchHint:'সরকারি সূত্রে খুঁজবে · আপনার ভাষায় উত্তর দেবে',sourcesTitle:'সরকারি সূত্র',verifiedLabel:'সূত্র যাচাই করা হয়'});
copy.bn.trust='প্রকল্পের বিবরণ এখানেই পড়ুন। সরকারি পাতা খুলবেন শুধু আপনি চাইলে।';
Object.assign(copy.ta,{brandCaption:'அரசு உதவி, உங்கள் மொழியில்',safeTitle:'உங்கள் தகவலைப் பாதுகாப்பாக வைத்திருங்கள்',askLabel:'திஷாவிடம் கேளுங்கள்',askTitle:'எந்த உதவியைத் தேடுகிறீர்கள்?',searchHint:'அரசு ஆதாரங்களில் தேடி · உங்கள் மொழியில் பதிலளிக்கும்',sourcesTitle:'அதிகாரப்பூர்வ ஆதாரங்கள்',verifiedLabel:'ஆதாரங்கள் சரிபார்க்கப்படும்'});
copy.ta.trust='திட்ட விவரங்களை இங்கே படிக்கவும். நீங்கள் விரும்பினால் மட்டுமே அரசு பக்கத்தைத் திறக்கவும்.';
copy.ta.stateLabel='உங்கள் மாநிலம் / யூனியன் பிரதேசம்';
copy.ta.privacy='உங்கள் கேள்வியும் தேர்ந்தெடுத்த மாநிலமும் பதிலுக்காக OpenAI-க்கு அனுப்பப்படும். ஆதார் எண், OTP, PIN அல்லது வங்கி விவரங்களைப் பகிர வேண்டாம்.';
Object.assign(copy.te,{brandCaption:'ప్రభుత్వ సహాయం, మీ భాషలో',safeTitle:'మీ సమాచారాన్ని సురక్షితంగా ఉంచండి',askLabel:'దిశను అడగండి',askTitle:'మీరు ఎలాంటి సహాయం వెతుకుతున్నారు?',searchHint:'ప్రభుత్వ మూలాల్లో వెతికి · మీ భాషలో సమాధానం ఇస్తుంది',sourcesTitle:'అధికారిక మూలాలు',verifiedLabel:'మూలాలు తనిఖీ చేయబడతాయి'});
copy.te.trust='పథకం వివరాలను ఇక్కడ చదవండి. మీరు కోరితేనే అధికారిక పేజీని తెరవండి.';
Object.assign(copy.mr,{brandCaption:'सरकारी मदत, तुमच्या भाषेत',safeTitle:'तुमची माहिती सुरक्षित ठेवा',askLabel:'दिशाला विचारा',askTitle:'तुम्हाला कोणत्या मदतीची गरज आहे?',searchHint:'सरकारी स्रोत शोधेल · तुमच्या भाषेत उत्तर देईल',sourcesTitle:'अधिकृत स्रोत',verifiedLabel:'स्रोत तपासले जातात'});
copy.mr.trust='योजनेची माहिती इथे वाचा. तुम्हाला हवे असेल तेव्हाच अधिकृत पान उघडा.';
for(const locale of Object.values(extraCopy)){
  locale.pension=locale.topicPension;locale.health=locale.topicHealth;
  locale.documents=locale.topicDocs;locale.work=locale.topicWork;
}
})();

